### ISSUE TITLE
Hide updates that are not applicable to platform/version

### ISSUE THREAD

**Issue by SanderGit** [rumboalla/apkupdater#14]
Currently the app suggests downloads for an incorrect platform (x86 vs. ARM/ARM64) and Android version (offers update to an app that requires Android 7 as minimum, while the device runs a lower version).

Please do not list updates that are not applicable to the device.

**Comment by DeicPro** [comment]
and can choose if want show different platform/version and app card show the info of what version/platform available.

**Comment by rumboalla** [comment]
APKMirror updater now supports filtering by architecture and api level. It will be include in next release.
