### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by Mrgts411** [rumboalla/apkupdater#188]
can you please add there features:

**1.** Built-in app browser to download APK's from APKMIRROR without the need to keep opening chrome each time.

**2.** a message that says "No new updates were found" when the updater finishes checking for updates and finds none. (i got confused and thought the app was broken) (**some like this:** http://i.imgur.com/hnxEmGS.png)

**3.** an option to disable android 8 (API 26) updates. (API 24/25 -> API 26 updates)

Also, thank you for making such a useful app 👍

**Comment by rumboalla** [comment]
1. I'm not going to implement this for several reasons:
* A lot of work to provide inferior browsing.
* Privacy. These sites have trackers, ads, etc. With a normal browser you can choose to block those but not with an embedded webview.

2. It's implemented in new release.

3. This is actually a server side bug in APKMirror. Artem told me they were going to fix it.
