### ISSUE TITLE
weird bug

### ISSUE THREAD

**Issue by Mrgts411** [rumboalla/apkupdater#192]
after using ur app to update apps (not system apps), my google play store crashes, google play store itself doesn't crash but if i browse apps in the store and click on **Read More** to see the changelog or description of the apps then it would crash.

***

| **Video** | |
| :--- | :---: |
| [![Google Play Store Bug](http://img.youtube.com/vi/TerItyUrTr0/0.jpg)](http://www.youtube.com/watch?v=TerItyUrTr0) | |

***

| Things i tried to do to fix this issue | |
| :--- | :---: |
| Clear app cache & data | Didn't Work |
| Clear dalvik cache from recovery | Didn't Work |
| Remove the app | Didn't Work |
| Reinstall from APKMIRROR | Didn't Work |

***

| Additional Info | |
| :---: | :---: |
| Phone | OnePlus 3 |
| Android | 7.1.1 |
| OS | OxygenOS 4.1.6 |

**Comment by Mrgts411** [comment]
**Update:** now twitter crashes every time i open it.

i redownloaded the newest version of ur app (1.5.6), to see if the bug was fixed, but nope, now twitter crashes every time i open it.

**Comment by rumboalla** [comment]
Are you doing root installs?

**Comment by Mrgts411** [comment]
nope, normal installs

**Comment by Mrgts411** [comment]
**Update 2:** i checked all apps on my phone to see which one doesn't work and here's the list:
- Twitter
- Discord (Crashed whole phone when i try to open app)
- PayPal
- OnePlus Community (Crashes when u click back arrow [thread content dont load])
- Gmail (opens then closes immediately)
- 9GAG
- Steam

i honestly don't know what to do, will do a factory reset in 2 weeks, i the mean time i will wait to see if u can figure out the problem.

**Comment by rumboalla** [comment]
I really doubt the app is causing all this.

**Comment by Mrgts411** [comment]
**Update 3:** It was the **Android System WebView**.

i disabled chrome, then updated it from google play store.

now everything is working fine.

**Comment by rumboalla** [comment]
Closing this then.

**Comment by Mrgts411** [comment]
u should add an option to exclude chrome, because when i updated it using ur app, it didnt update it's webview (in nougat chrome runs webview, no longer a separate app) so that's why this issue happened.

Also, please add an option to search for app in **Installed** tab.
