### ISSUE TITLE
Misleading sources: evozi not google play store

### ISSUE THREAD

**Issue by rancidfrog** [rumboalla/apkupdater#2]
Description says source is play store but in fact is evozi?
```
static final private String BaseUrl = "https://play.google.com/store/apps/details?id=";
	static final private String DownloadUrl = "https://apps.evozi.com/apk-downloader/?id=";
```
Apps that actually use source, however needs a google account in order to download

- https://github.com/onyxbits/Raccoon
- https://github.com/egirault/googleplay-api
- https://github.com/jackpf/ApkDownloader
- https://github.com/jlindsey/ApkDownloader

**Comment by rumboalla** [comment]
It checks for the app version on Google Play, but sends you to download the app through evozi website where you do not need a google account. This is a bit misleading and I shall make it more clear.

**Comment by rumboalla** [comment]
It is now much more clear. Thanks!
