### ISSUE TITLE
It does not  install anything

### ISSUE THREAD

**Issue by gerroon** [rumboalla/apkupdater#201]
Hi

I can get all the updates from Gplay but when I try to install any app or apkupdater itself, it says it downloaded the app but when I click on the ap p in the tray it says it cant find the file. I tried the root install method, it still does not work. With the root method it says the app is updated but actually no update/install happens.

And it crashes like in https://github.com/rumboalla/apkupdater/issues/200 if no root method isued.

Please see the Yalp app on Fdroid for proper installing from Gplay. That app seems to work for me.

I am on 5.1 Samsung phone

thanks

**Comment by rumboalla** [comment]
Fixed in dev branch.

**Comment by gerroon** [comment]
Thanks man
