### ISSUE TITLE
Please add an update from the following locations!!

### ISSUE THREAD

**Issue by Alsidi-Group** [rumboalla/apkupdater#202]
Hello dear ..
------------
Please add an update from the following locations
http://www.apklinker.com/
http://apk-dl.com/
https://sameapk.com/
http://www.revdl.com/
https://www.allfreeapk.com/
http://www.apktrunk.com/
-----------

**Comment by rumboalla** [comment]
These sites don't offer anything over the current sources and some of them are clearly knockoffs.

**Comment by jerryn70** [comment]
@rumboalla what about adding fossdroid.com ?
