### ISSUE TITLE
Avoid Multiple Download if unknown source is turned off

### ISSUE THREAD

**Issue by jerryn70** [rumboalla/apkupdater#204]
Today I tried to update an app. I have clicked the update button and the download got started, after 100% of download it shows turn on unknown source to install. I have turned on the unknown source and came back. But again I need to start the download process to install the app. 
I hope you understand what I mean.

**Comment by rumboalla** [comment]
You just need to turn unknown sources once.

**Comment by jerryn70** [comment]
after turning ON unknown source and when I click install i will again download the file.
