### ISSUE TITLE
Direct Download Apps from Update Source

### ISSUE THREAD

**Issue by jerryn70** [rumboalla/apkupdater#205]
Please make an optional option to download apps directly from apkmirror , apkpure etc update source. 
When a download is redirected to a site, for a noobie user it is so hard to find the correct apk file. 

Example when a download is redirected to apkmirror , it is hard to find the apk download link because there are many other variants/versions etc etc links.
Maybe experts don't have any problems but noobies or girls face problems.

So it will be great if you add direct download option.

**Comment by rumboalla** [comment]
Can't go around stealing people's bandwidth.
