### ISSUE TITLE
Ignore app versions

### ISSUE THREAD

**Issue by keatonthewise** [rumboalla/apkupdater#208]
A way to ignore major.minor versions of an app would be ideal in situations where the version in question is still compatible with the requested device's architecture/API but contains unwanted/unneeded features or breaks functionality.

A previous major.minor app version may still continue to receive updates, so a user may want to continue receiving update notifications for this version(s) when they are available.

**Comment by rumboalla** [comment]
Duplicate https://github.com/rumboalla/apkupdater/issues/45
