### ISSUE TITLE
Translation credits

### ISSUE THREAD

**Issue by rumboalla** [rumboalla/apkupdater#211]
If you have translated or collaborated in a translation, write here the name and optional link that you want to display in the credits.

Example:
rumboalla, English, https://github.com/rumboalla

**Comment by mihey4ik** [comment]
mihey4ik1, Russian, https://4pda.ru/forum/index.php?showtopic=783384

**Comment by Primokorn** [comment]
Primokorn, French, [https://t.me/Primokorn

**Comment by Huaji** [comment]
Zhiyuan Wang,Chinese (simplified),http://weibo.com/321134526

**Comment by Deltafox79** [comment]
DeltaFoX - Italian https://www.dfox.it

**Comment by ToxxMe** [comment]
Toxx, German, https://goo.gl/xQGYH3

**Comment by RuanF69** [comment]
RuanF, Afrikaans, https://ruanf.co.za

**Comment by Cortex-A93** [comment]
Aydogan Aykanat, Turkish, http://aydoganaykanat.com/

**Comment by edentw** [comment]
@rumboalla 
Does the APP still have maintenance? Because the translation needs to be supplemented.
