### ISSUE TITLE
App updates are found linking to version '?', only option is 'Install'

### ISSUE THREAD

**Issue by crkellen** [rumboalla/apkupdater#213]
I cannot find any information on this. I often get updates that are one number or more increments that only have the option to Install.

Most of the time they don't install because incompatible with my phone, or it says the file is corrupted. To my knowledge there are no .app files downloaded as I delete the files after installing.

It shows my version (xxxxx) → ? (xxxxy)

**Comment by Mrgts411** [comment]
same here, i just skip those.

**Comment by rumboalla** [comment]
This is normal. It's not possible to get the version string without doing an extra network call for every app.
The number in the parenthesis is the version code of the app.
