### ISSUE TITLE
VT Warning

### ISSUE THREAD

**Issue by IzzySoft** [rumboalla/apkupdater#216]
I've just scanned the latest `.apk` with VT, [here are the results](https://www.virustotal.com/de/file/e8834161ff7dd1c973773ccbfa579080b21f1b4093836308b364b180fbe7faf2/analysis/1499435203/). Any idea about those 3 hits? One of them was [already reported](https://www.virustotal.com/de/file/0aa6988b3bdf5065ec58b7604d2f6557aa83efe0bce4133817b8003d9ee1bbc9/analysis/1499190722/) for the previous version.

**Comment by rumboalla** [comment]
The app is clearly a virus.

**Comment by IzzySoft** [comment]
@rumboalla I somehow doubt that (never heard of a virus on Android). Besides, it's the `.apk` file you published here for your own app. But if you take a decent report as a joke, I'm not sure how to trust the app indeed – and must warn my "audience" not to use it.

Misunderstanding? Or did you mean it?

**Comment by rumboalla** [comment]
Some antivirus, with names that seem generated with a random name generator, and poor heuristics think my app is a virus...nothing I can do about it.
My best guess is that these antivirus don't like the code to install apps as root, but who knows.
In any case I'm not going to do anything about it and that's why this is closed.

**Comment by IzzySoft** [comment]
@rumboalla that's a much better explanation, thanks. And I'm aware that some of those 50+ scanners at VT are, let's say, less reliable (e.g. I tend to ignore WhiteArmor for which almost every second app is "PUP" (a Potentially Unwanted Program). BKAV also has false-positives more often than others, to my experience. But when I see TrendMicro joining the party of reporters (even if it's just their HouseCall), that raises more than one eyebrow and causes concern.

So if you are sure this is a false alert and, as a result, don't want to act on it: understood (after all, what should you do?). Thing is just users see "Oh! 3 scanners report it suspicious!", and make up a different opinion. I've left a comment on those results pointing here, so they at least get some background before doing so.
