### ISSUE TITLE
Google Account Login issue

### ISSUE THREAD

**Issue by Deltafox79** [rumboalla/apkupdater#218]
I have this issue on v1.0. 5.10

1. The login into my Google account doesn't work for me. I type in my email and password, it starts the Two-factor-authentification, I type in the code but then it's an endless loading page. 

2. Get a malformed request for Google play services for instant apps.

**Comment by crkellen** [comment]
I have this issue as well since 5.09.

**Comment by Mrgts411** [comment]
i have the first issue as well, already reported it but it was ignored.

**Comment by rumboalla** [comment]
There's two ways to do this:
1) Enable "Allow less secure apps" in your Google account settings.
OR
2) Set up a one time password on the 2-step verification settings of your Google account.

I'll add this information somewhere in the app, because it's a bit hard to figure out.

**Comment by Mrgts411** [comment]
the "Allow less secure apps" option, is ur app not secure enough or is it just google not allowing it because it's not a well known app?
or is it because it's a third party apk (not from google play store)?

**Comment by crkellen** [comment]
I was wondering, why would I want to use my Google account? What are the differences between using the public and my own?

**Comment by rumboalla** [comment]
@Mrgts411 
You can find more info here: https://security.stackexchange.com/questions/66025/what-are-the-dangers-of-allowing-less-secure-apps-to-access-my-google-account

@crkellen 
Paid apps for example.

**Comment by Mrgts411** [comment]
@rumboalla 
So you cant make the login more secure, so it can work without doing the ways u listed above?

**Comment by rumboalla** [comment]
Closing this.
This one will be referenced from the app: https://github.com/rumboalla/apkupdater/issues/223

**Comment by jvschiavo** [comment]
Why can't you make it compatible with "modern security standards" or maybe compatible with OAuth?
