### ISSUE TITLE
AMOLED Black Theme

### ISSUE THREAD

**Issue by crkellen** [rumboalla/apkupdater#219]
The Dark Droid theme is pretty good but I think having a OLED-friendly Dark Theme would be nice. The bloody void is incredibly difficult to use as it's so hard to look at.

Having a simple theme like Dark Droid, but all of the dark parts are #000000 would be appreciated.

**Comment by tetsuo55** [comment]
I support the black theme as an addition to the astronomer theme (bloody void)

**Comment by rumboalla** [comment]
Added
