### ISSUE TITLE
Exclude other architecture also excludes noarch

### ISSUE THREAD

**Issue by tetsuo55** [rumboalla/apkupdater#221]
When selecting this option i expect only incompatible archs to be ignored.

However it seems to ignore everything.

For my arm64 galaxy s7 i expect the following to not be excluded:
Arm
Arm64
Noarch

Be excluded:
X86
X86_64
Mips
Mips64

**Comment by tetsuo55** [comment]
Actually when i think about it this might be better:

*Detect the arch of the currently installed app
*Filter the results to only show updates that match the current app's arch

I guess the same could be done for dpi and sdk

**Comment by rumboalla** [comment]
Examples?

**Comment by tetsuo55** [comment]
Examples on xda
https://forum.xda-developers.com/showpost.php?p=73006520&postcount=370

**Comment by rumboalla** [comment]
I think I fixed this one too now.

**Comment by tetsuo55** [comment]
Ok i will test in the next build and let you know

**Comment by tetsuo55** [comment]
The new build fixed this issue
