### ISSUE TITLE
How to setup your Google account

### ISSUE THREAD

**Issue by rumboalla** [rumboalla/apkupdater#223]
# Method 1
- Go to [Google Account Settings](https://www.google.com/settings/account),
- Go to **Security**.
- Enable **Allow less secure apps**.

# Method 2
- Go to [Google Account Settings](https://www.google.com/settings/account),
- Go to **Security**.
- Go to **2-Step Verification**.
- Go to **Application Specific Passwords**.
- Create a password.
- Use the password from the app.

**Comment by jvschiavo** [comment]
@rumboalla Why can't you make it compatible with "modern security standards" or maybe compatible with OAuth?

Not trying to sound rude (tough I always think I do anyway...)

**Comment by Laicure** [comment]
@jvschiavo I don't know where to look at but this one [YalpStore](https://github.com/yeriomin/YalpStore) uses the standard login thing and nothing else (I think). I hope that helps for @rumboalla.

**Comment by azumukupoe** [comment]
It's not working

**Comment by patrickdrd** [comment]
+1 

even though I've got "Allow less secure apps: ON"

**Comment by lumbo7332** [comment]
Not working for me. I created an app password and entered it along with my username. Nothing.

**Comment by puppykickr** [comment]
I don't know if this is the cause, but Google does not allow 3rd party apps to sign into Google accounts.

I have seen a pop up saying as much each time I have used an app to attempt this.
