### ISSUE TITLE
Updates list doesnt refresh to sorted top entry

### ISSUE THREAD

**Issue by tetsuo55** [rumboalla/apkupdater#224]
When checking for updates apkupdater will lock its focus on the first update it finds and when the check is done sort all the results alphabetically.

The issue is that instead or focusing on the first/top entry of the sortes list the focus remains on the first found update regardless of where it fits alphabetically

Could this be changed so that after sorting it refocusses on the first entry at the top?

For example and screenshots see xda here. 

https://forum.xda-developers.com/showpost.php?p=73006795&postcount=371

**Comment by rumboalla** [comment]
Fixed
