### ISSUE TITLE
APK Updater doesn't ask for root permissions no matter what.

### ISSUE THREAD

**Issue by Nikki1993** [rumboalla/apkupdater#226]
Hello there,

Running AOSPA 7.2.0 with Magisk v13.2 systemless. Can't get APK Updater to ask for root permissions when enabling root installation. Keep getting su rejected in the magisk logs. What gives or how to make APK Updater ask for root permissions?

Tried reinstalling the app, clearing app data etc, nothing. Root on its own works, as I have 2 other apps requiring root permissions.

**Comment by rumboalla** [comment]
This looks like an issue on your end,

**Comment by Nikki1993** [comment]
I am not so sure. Eventually, when I had APKUpdater in the foreground and there was an app to update if finally asked, but it never asked for root permission when I checked the box labeled as require root. Why not ask for root permissions when enabling such options?

**Comment by rumboalla** [comment]
That's actually a good point. I'll make some changes and check for root once the checkboxes are selected.
