### ISSUE TITLE
Google Play Games android tv variant listed as update for a phone

### ISSUE THREAD

**Issue by tetsuo55** [rumboalla/apkupdater#231]
in the attached screenshot you can see my up to date version of google play games is listed as having an update available.

on clicking the link i see that its for android tv

link: https://www.apkmirror.com/apk/google-inc/google-play-games-android-tv/google-play-games-android-tv-5-2-25-release/

screenshot: http://imgur.com/a/8PI1K

**Comment by rumboalla** [comment]
It happens with several apps and it's an APKMirror issue.
