### ISSUE TITLE
Show App icon on Search results

### ISSUE THREAD

**Issue by jerryn70** [rumboalla/apkupdater#233]
When i search for apps ,the result shows a list of apps but it's hard to find out the real app which iam looking for because there is no app icons .

**Comment by rancidfrog** [comment]
Also,
A way too see: 
- app details/description section
- latest Update changelog (What's New section right before Additional information section)
- maybe even Additional information: Updated, Current Version, Permissions

This also applies when an updated is available: Having update changelog can be handy
