### ISSUE TITLE
Issues when using common google id: Wrong version apk downloaded

### ISSUE THREAD

**Issue by rancidfrog** [rumboalla/apkupdater#234]
When using the provided common google id it can cause wrong version of apk to be downloaded.
I downloaded foobar2000 update using both common google id and my own google id and the first apk was with armv7 while the 2nd was armv8 (the correct apk is armv8 for device using app).
Since foobar is a multemedia app therefore this applies but other app like note app seem to be identical.
![](https://s3.postimg.org/u3g9th70j/Screenshot_20170802-194647_01.png)

A couple of observations:

- **Why are downloaded files stored the following way and not filename with apk extention in case we want to backup?**

![](https://s3.postimg.org/6b6yhy4zn/Screenshot_20170802-194721_01.png)

The 2 files that are 3.2 mb are identical, (same hash values) but have different filenames.
The other 2 files (5.5mb vs 5.7mb) are the same app but one with arm7 and the other arm8

- **When using own google id, there are times when signing in does not work, does that mean it will use default google accounts?
If that is the case can we have an option to disable common google id as wrong apk version can be downloaded, as mentioned above.**

**Comment by rumboalla** [comment]
The phone profile has been updated by someone else. Not much can be done about this except for using own account.

**Comment by rancidfrog** [comment]
But, can you add some kind of header/info to show that you are currently connected to own google account? (Inaction bar?)

Maybe also, an option/checkbox/switch in settings to __only__  use own id for updates and _not_ use common ods at all.
