### ISSUE TITLE
App does not check cache for file before downloading

### ISSUE THREAD

**Issue by rancidfrog** [rumboalla/apkupdater#235]
If you click cancel instead of install, then recheck update, file gets downloaded again.
This can be repeated again and again:
![](https://s4.postimg.org/9wrxie6q5/Screenshot_20170803-002343_01.png)

As seen from above, files with same size are identical.
If file is saved with package name and version code, instead of random format, then you can first check cache if file exists before downloading again.

This is not a major concern, but when using data wastes bandwidth. Also, bad practice.

**Comment by jvschiavo** [comment]
I think this is the major issue right now that should be adressed.

**Comment by rancidfrog** [comment]
Also,
Cache does not seem to be emptied/deleted with time:

![](https://s29.postimg.org/idymym37r/Screenshot_20170818-134033_01.png)

**Comment by jvschiavo** [comment]
Thumbs up.

@rumboalla Please make this a priority.
