### ISSUE TITLE
Error 403: Forbidden

### ISSUE THREAD

**Issue by jvschiavo** [rumboalla/apkupdater#237]
I get this when I try to install some apps. Why?

![image](https://user-images.githubusercontent.com/20977075/28953123-715a761e-78ac-11e7-9518-19a6f64a7cef.png)

**Comment by rumboalla** [comment]
Please elaborate.

**Comment by jvschiavo** [comment]
When trying to install (update) YouTube Music, Hound and maybe some other apps clicking on *INSTALL* I get Error 403: Forbidden. I think it is using through Google Play option in settings.
Maybe it is because I live in Brazil and these apps aren't available here?

**Comment by jvschiavo** [comment]
Could you please review this issue?
