### ISSUE TITLE
Question about using my own Google account

### ISSUE THREAD

**Issue by jvschiavo** [rumboalla/apkupdater#238]
![image](https://user-images.githubusercontent.com/20977075/28953497-d7047dd2-78ae-11e7-9f21-ad537ba8b0bc.png)
What are the advantages and disadvantages of using this option?

Also, is this the correct place to ask questions? I have lots of questions to ask but I didn't find any other place to do it.

**Comment by Primokorn** [comment]
Support thread for further questions: https://forum.xda-developers.com/android/apps-games/app-apkupdater-t3444517
You may find the answer of the current question.

**Comment by rumboalla** [comment]
As Primokorn said, this is not the place.
