### ISSUE TITLE
Small UI suggestion

### ISSUE THREAD

**Issue by jvschiavo** [rumboalla/apkupdater#239]
![image](https://user-images.githubusercontent.com/20977075/28953548-38a90fb2-78af-11e7-8df6-35cf47cfaa79.png)
![image](https://user-images.githubusercontent.com/20977075/28953550-3bc6f83a-78af-11e7-97ea-07a97ec838c0.png)

I think you should remove the asterisks before and after words/tenses. They are everywhere in the UI, and IMHO they make things look uglier, there is no need of them. I think other people will agree with me.

**Comment by rumboalla** [comment]
This is strings marked as untranslated.

**Comment by jvschiavo** [comment]
Oh, I didn't even notice. Thank you. If you need help with translation you can ask me. :)
