### ISSUE TITLE
UI suggestion about tabs

### ISSUE THREAD

**Issue by jvschiavo** [rumboalla/apkupdater#240]
![image](https://user-images.githubusercontent.com/20977075/28953607-a4b76014-78af-11e7-99eb-3ff47873e1c4.png)

Do we need tabs at all in this app? I don't think so.
The Search tab could easily be moved to the top right corner in the place of the settings icon, which could be moved to the 3 dots drop-down menu, with this order: Logs, Settings, About.

Also, there is no need to installed tab too. It could be merged with Updates. Just put apps with updates at the top and other below. Maybe like APK Track or Play Store does.
![image](https://user-images.githubusercontent.com/20977075/28953705-558a22dc-78b0-11e7-9e16-5806234652c6.png)

Also, you could make cards smaller to fit more apps on screen at the same time, maybe the same size of the apktrack.

What do you think?

**Comment by rumboalla** [comment]
Not planning to redo the main structure of the app for the moment.
