### ISSUE TITLE
Suggestion: Report wrong app button

### ISSUE THREAD

**Issue by jvschiavo** [rumboalla/apkupdater#241]
All these 3 apps are being suggested as updates available while they are wrong versions.
Crunchyroll and Yotube are showing TV versions, while Handwriting Input is the wear version.
![image](https://user-images.githubusercontent.com/20977075/28959502-15973608-78d1-11e7-86d1-dd21fd3efc14.png)

Suggestion: Maybe a quick long-press to report the app can solve this issue? 

**Edit:** Sorry, the youtube was my mistake. The others are indeed wrong.

**Comment by rumboalla** [comment]
Signature validation will be added soon so this won't be needed.
