### ISSUE TITLE
Redirect APKMirror link to the latest download page

### ISSUE THREAD

**Issue by jvschiavo** [rumboalla/apkupdater#242]
APKMirror pages are slow and cluttered, and we have to go through 3 of them until we can download our app. I know you don't want to provide direct download so they can get ad revenue, but could you please redirect us to the the latest download page? This way we get our download faster and they still make revenue for that page.
![image](https://user-images.githubusercontent.com/20977075/28959789-613db63a-78d2-11e7-9c59-c2108f02c9f0.png)

**Comment by rumboalla** [comment]
As requested by APKMirror, I can't do this.
