### ISSUE TITLE
[Feature request] Link Github repo (Releases) for specific apps

### ISSUE THREAD

**Issue by Primokorn** [rumboalla/apkupdater#243]
Hi,
I'd like to check updates for specific apps that are only hosted on Github.
Example: https://github.com/MrBIMC/RunInBackgroundPermissionSetter/releases

Could APKUpdater check updates of Github repos? (releases tab)

Thank you.

**Comment by TPS** [comment]
@Primokorn I took your idea & expanded it in my RFE @ #258.  Feel free to elabore further upon it. :bow:

**Comment by Primokorn** [comment]
@TPS Actually we have no news from @rumboalla for months so we don't know if the project has been discontinued.

**Comment by TPS** [comment]
Well, _that's_ a problem!  D'ya know if there're any devs willing to work on a current fork? [I'm part of an org set up _specifically_ for such cases!](https://github.com/rejuvenate/rejuvenate)

**Comment by TPS** [comment]
@rancidfrog, @Erma318, @koroshiya: From the [network graph], y'all may be actively working on this.  Are you interested?
>Well, _that's_ a problem!  D'ya know if there're any devs willing to work on a current fork? [I'm part of an org set up _specifically_ for such cases!](https://github.com/rejuvenate/rejuvenate)

**Comment by koroshiya** [comment]
@TPS I'm not actively working on this, just the occasional pull request, but if another fork takes over I'm happy to submit PRs there instead.
