### ISSUE TITLE
Connecting to own ID is problematic

### ISSUE THREAD

**Issue by rancidfrog** [rumboalla/apkupdater#244]
I am using only Google play updates, own Google play id.

How can I know if app is using own Google ID vs common ID?
**When trying to reconnect using own Google ID I have to manually disable and then re-enable less secure settings each time I want apkupdater to register login**, otherwise I get error attempting to get token.
![](https://s1.postimg.org/ko6stgndb/Screenshot_20170808-094640_01_01_01.png)

**Comment by rumboalla** [comment]
You can try using app specific passwords if you don't want to enable/disable less secure.

**Comment by rancidfrog** [comment]
I do not see option of app specific passwords.

_Sent from my OnePlus ONEPLUS A5000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by rancidfrog** [comment]
I do not have app specific password option available, when checking security settings on accounts.google.com

_Sent from my OnePlus ONEPLUS A5000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by rancidfrog** [comment]
I do not have app specific password option available, when checking security settings on accounts.google.com
