### ISSUE TITLE
UpdaterService: Unable to get GooglePlayApi

### ISSUE THREAD

**Issue by rancidfrog** [rumboalla/apkupdater#253]
When trying to check for updates, recently I keep getting update check finished with 1 error:

![](https://i.imgur.com/7WZl97S.png)

Log shows:

![](https://i.imgur.com/UVuAL1t.png)

It seems to be a problem with using own Google play account.
As I can temporarily fix it sometimes by logging on to accounts.Google.com and disable/enable allow less secure apps and then deselecting/selecting 'Use own Google account' in settings which prompts for login to get token.
After I am able to login, update check works for a while before I get error again.

**Comment by rancidfrog** [comment]
@rumboalla 
This might be solved by updating library yeriomin:play-store-api to latest 0.29 release and making sure following procedure to ensure longer ttl:

- https://github.com/yeriomin/play-store-api/commit/6544937ac2b9c513044d2b510b835c6e7bc2b8da
- https://github.com/yeriomin/play-store-api/commit/7517d9e29e9099555ad7a15bb601c36a26b5a72f

**Comment by rob-savage** [comment]
@rancidfrog 0.29 release of yeriomin:play-store-api breaks apkupdater 1.5.11 from what I can see.  Did you get it working?

**Comment by rancidfrog** [comment]
No.
Changes needed to be made.
As library has some modifications.
Big jump: from 0.18 to 0.29

**Comment by patrickdrd** [comment]
any update on this? 
any new release out?

**Comment by hirenshah** [comment]
Does anyone have a fix for this please?
