### ISSUE TITLE
[Feature request] App opt-in to scan for updates

### ISSUE THREAD

**Issue by eugf** [rumboalla/apkupdater#262]
Would it be possible to have a toggle to change from the current mode which seems like an opt-out selection by ignoring apps which you don't want to have updated, to only scan for apps you've specifically opted-into that you want updated? I think this would be beneficial for those users who only have a few apps which they want updated through apkupdater while the rest are already covered with other app stores.

**Comment by jessehouwing** [comment]
I'd love that. Or to just scan for apps that aren't linked to the Google Play Store on the device?
