### ISSUE TITLE
Wrong version number in APK

### ISSUE THREAD

**Issue by IzzySoft** [rumboalla/apkupdater#27]
The latest version (1.3.4) carries the wrong version number internally:

    package: name='com.apkupdater' versionCode='3' versionName='1.3.3' platformBuildVersionName='7.1.1'

Nothing critical, just as a note. Might cause problems when updating the app on-device.

**Comment by rumboalla** [comment]
Should be ok now.

**Comment by IzzySoft** [comment]
It is – thanks!

**Comment by TPS** [comment]
@IzzySoft Is something w/ the current version numbering why your repo isn't picking up the recent [pre-releases (αs & β)](https://github.com/rumboalla/apkupdater/releases/) or is it something else?

**Comment by IzzySoft** [comment]
It's **pre** releases, so the app is most likely configured (on my end) to skip them, which is the default. Additionally, And the alphas only had debug versions attached. Apart from that: I've just manually fetched the latest beta and run my scanner over it: no issues that I can see, so it's simply the "pre".

**Comment by TPS** [comment]
@IzzySoft Thanks very much for checking into it.  From this point, assuming @rumboalla continues to sign non-debug β versions (though sensibly here marked prerelease), is there a way for your repo to pull them automatically, or must they be manually pulled until they're switched to release?  Also, would you mark these in your repo as unstable releases until the eventual final 3.0 arrives?

**Comment by IzzySoft** [comment]
I can switch the toggle to NOT ignore pre-releases, but I'd only do that if @rumboalla agrees. And no, I have no way to mark those as "unstable" – which is why I must insist on the author's agreement :wink:

*Looky-lookie:* There's no Fastlane set up here. Else this could be indicated by the per-release changelogs.

@rumboalla if you wish I can send you a PR with a "starter package" of what I've set up with my repo here. You could then e.g. use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for guidance to build upon that. The added plus: **you** can define how your app is presented here, as my updater would pull that along with each release.

**Comment by rumboalla** [comment]
> I can switch the toggle to NOT ignore pre-releases, but I'd only do that if @rumboalla agrees. And no, I have no way to mark those as "unstable" – which is why I must insist on the author's agreement 😉
> 
> _Looky-lookie:_ There's no Fastlane set up here. Else this could be indicated by the per-release changelogs.
> 
> @rumboalla if you wish I can send you a PR with a "starter package" of what I've set up with my repo here. You could then e.g. use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for guidance to build upon that. The added plus: **you** can define how your app is presented here, as my updater would pull that along with each release.

I wouldn't change anything. beta-02 is most likely going to be the last pre-release.

**Comment by IzzySoft** [comment]
Great news, thanks @rumboalla!

**Comment by TPS** [comment]
> It's **pre** releases, so the app is most likely configured (on my end) to skip them, which is the default. Additionally, the alphas only had debug versions attached.

@IzzySoft Is the only remaining issue (now that there's a release) is the APK is a debug version?

**Comment by IzzySoft** [comment]
@TPS depends on what you consider an issue. Being marked for debug strangely can be seen as a feature today, to, with Android-12+ no longer allowing to backup apps **not** marked such via `adb backup` :see_no_evil:

**Comment by TPS** [comment]
@IzzySoft I mean for your repo to pick it up?

**Comment by IzzySoft** [comment]
Huh? My updater will pick up what's at the "stable" release. If it's a debug build, it will simply get the `ApplicationDebuggable" mark. That release has just been tagged 19h ago, after the last updater run – so you'll have to wait another 30min for it to become available. If the versioning is correct :see_no_evil: Updater should start right… oh, has started right now.

**Comment by TPS** [comment]
@IzzySoft I _was_ going to apologize for being too hasty, but _now_ I'm confused. 2½ hours after scheduled update & still not picked up?

**Comment by IzzySoft** [comment]
Maybe it was set to monthly updates as there were none for a while? Let me check… Yupp. There was no update since 2021-01-03, so update check was set from daily to monthly. I've triggered an update manually now (and while on it, also updated the screenshots). Will show up with the next sync then.

@rumboalla what interval do you think will be there between updates now, just round-about? More or less than once a month? Just asking so I re-adjust the interval for my update checker accordingly. And while on it, what do you think about establishing Fastlane structures, so you can control description and graphics of the listing? See e.g. my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) which is available for guidance; I could also send a PR with what I've set up here as "starter kit" if you wish.

**Comment by rumboalla** [comment]
> Maybe it was set to monthly updates as there were none for a while? Let me check… Yupp. There was no update since 2021-01-03, so update check was set from daily to monthly. I've triggered an update manually now (and while on it, also updated the screenshots). Will show up with the next sync then.
> 
> @rumboalla what interval do you think will be there between updates now, just round-about? More or less than once a month? Just asking so I re-adjust the interval for my update checker accordingly. And while on it, what do you think about establishing Fastlane structures, so you can control description and graphics of the listing? See e.g. my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) which is available for guidance; I could also send a PR with what I've set up here as "starter kit" if you wish.

Once a week or so, at least for now.
I'll add the Fastlane stuff to my TODO. Your PR is welcome of course.

I'm planning to add support for more F-Droid repos, is it ok to add yours?

**Comment by IzzySoft** [comment]
> Once a week or so, at least for now.

Cool. I've re-enabled the daily checks then.

> I'll add the Fastlane stuff to my TODO. Your PR is welcome of course.

Will prepare it now.

> I'm planning to add support for more F-Droid repos, is it ok to add yours?

Sure, you wouldn't be the first. Obtainium does as well. But thanks for asking!
