### ISSUE TITLE
Add more sources

### ISSUE THREAD

**Issue by Madis0** [rumboalla/apkupdater#271]
I can see you've resumed the work on this app (v2 looks great!), so you might want to get some changes from a fork to upstream: https://github.com/hemker/apkgrabber 

Most importantly, some app sources have been added:

- ApkPure 
- Google Play 
- Uptodown

**Comment by bobel640** [comment]
there's an option to add samsung app store to the sources?

**Comment by bobel640** [comment]
add APKCombo

**Comment by d-l-n** [comment]
Would it be possible to download apk from apkmirror without left apkupdater?

**Comment by hemker** [comment]
@d-l-n that's not possible due to APKMirror download restrictions. You have to visit the site and see some ads.

**Comment by EngineerGlitch** [comment]
I think APKMirror is more than enough it's a reliable source, unlike Uptodown and APKPure can contain adware, google play has been added, I recommend you to close this issue
