### ISSUE TITLE
2.0.0-beta2 versioncode and versionname the same as 2.0.0-beta1

### ISSUE THREAD

**Issue by archon810** [rumboalla/apkupdater#272]
https://github.com/rumboalla/apkupdater/releases/tag/2.0.0-beta2 is the same as https://github.com/rumboalla/apkupdater/releases/tag/2.0.0-beta1: shows as 2.0.0-beta2 and versioncode 30.

P.S. Glad you are back @rumboalla! Perhaps we could pick up our conversation on Telegram where we left off to make apkmirror integration the best it can be? You deleted your Telegram account, but I hope you can rejoin and hit me up at @archon810.

**Comment by rumboalla** [comment]
Should be fine with new beta version.
Account is probably gone due to inactivity, I'll have to make a new one.

**Comment by archon810** [comment]
Alright, feel free to hit me up on Telegram when you make a new account.
