### ISSUE TITLE
beta4 force close

### ISSUE THREAD

**Issue by OMassalia** [rumboalla/apkupdater#274]
New beta4 force close at the openning

**Comment by rumboalla** [comment]
Please provide logs and more information.

**Comment by OMassalia** [comment]
[Log_2019-12-03_11-12-17.txt](https://github.com/rumboalla/apkupdater/files/3916018/Log_2019-12-03_11-12-17.txt)
I open app and few seconds after, app force close

**Comment by rumboalla** [comment]
Is this fixed with beta7?

**Comment by OMassalia** [comment]
I think yes. At this time no force close. Thanks a lot

**Comment by rumboalla** [comment]
Enjoy!
