### ISSUE TITLE
Add fast scroller

### ISSUE THREAD

**Issue by rancidfrog** [rumboalla/apkupdater#276]
With large app list it can be a hassle to scroll to bottom, having fast scroller can be helpful which allows dragging of scroll bar quickly 

I.E.
Scroll bar normal,
![](https://i.imgur.com/Au7ews9.png)

While dragging with accent colour,
![](https://i.imgur.com/SKCVW8d.png)

**Comment by rumboalla** [comment]
Moved to https://github.com/rumboalla/apkupdater/discussions/393
