### ISSUE TITLE
why add tracker

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [rumboalla/apkupdater#277]
why found tracker apps 

328 tested signatures on 4635 classes
(1079347)

Startapp

*Startapp
557com.startapp.android.publish

file:///data/app/com.apkupdater-IhsQRVyOpMRTuu-_kTIDeg%3D%3D/base.apk

MD5sum: 98aa3645046bca83bce49b0122c6c238
SHA1sum: 01ed5df5fd8eff677c4f8631c06c67ef998467b2
SHA256sum: 5015e4cf634bae5fb18d7773800901e5731bd0efc2f6a9a26276da2acf35ff51

CN=APKUpdater

SHA256withRSA

CERTIFICATE fingerprints: 
md5: d74bbd42d423ce224b377b51eeaf3cf4
sha1: 608e9e3e75d550467cd33af31ebbaa53f889c2af
sha256: 00e352c614669c1897293f8b4d50f9c154026a319a0c32b8a7585cca0593c3ec

**Comment by rumboalla** [comment]
It's the ad sdk.
I haven't really decided what to do with them yet, I may remove them or make them optional or something else.
