### ISSUE TITLE
Request: allow to exclude apps that were installed from the Play Store

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [rumboalla/apkupdater#278]
Because the Play Store already handles those.
Please allow to show and handle only those that aren't available on the Play Store.

**Comment by tjsuominen** [comment]
This would be great addition to improve the UX.

**Comment by AndroidDeveloperLB** [comment]
You can check the installation source of the apps. It's much quicker than checking it all via the Internet.
It's less reliable though, because just because an app was installed on the Play Store doesn't meant he Play Store still has the app and will update it (it might have banned it).
Plus there is the rare case that the user has set it by force, as if the app was installed from the Play Store. But this is quite rare.

I suggest to have an option on the settings to configure how to check it. I think that for most cases, the installation source alone is enough, instead of checking each app if indeed it still exists on the Play Store.

**Comment by rumboalla** [comment]
This is implemented now: https://github.com/rumboalla/apkupdater/commit/4ba0cfe1f385f6cdd28ea45f0d48c642363db0a2

**Comment by AndroidDeveloperLB** [comment]
On the newest release?
And does it also check for updates... of itself?

**Comment by rumboalla** [comment]
It will be included in next version.
And yes there is a self update check.

**Comment by AndroidDeveloperLB** [comment]
Good.
Here's one for you:
https://9gag.com/gag/a857BA6
