### ISSUE TITLE
Search Function

### ISSUE THREAD

**Issue by EMK2000** [rumboalla/apkupdater#28]
Could you provide a function, that is not only search for updates for installed apps, but also a search function for searching new apps? 

For example, if my phone does not have WhatsApp installed, then I can search for the keyword WhatsApp in your app, and then I can choose to download it from Play Store / APKMirror / APK Pure. 

I know that in since sense it is not an updater, but a downloader. But it is easier to search and download in one app rather than in three websites / apps.

**Comment by rumboalla** [comment]
This is now implemented in the dev branch.
