### ISSUE TITLE
Bug: when choosing to install from Play Store, it doesn't do it, and it shows wrong or no progress

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [rumboalla/apkupdater#280]
See attached video.

[device-2019-12-12-162626.zip](https://github.com/rumboalla/apkupdater/files/3956175/device-2019-12-12-162626.zip)

When I choose to install from Play Store, I expect it to really install from there. 
The current way... I have no idea how it gets the APK from, and I don't think the Play Store app registers me as one who installed the app from there and will allow me to review it etc...

Not only that, but on some cases it doesn't show any indication of what's going on, or shows indication of progress on the wrong time...

**Comment by rumboalla** [comment]
Fixed https://github.com/rumboalla/apkupdater/commit/b4b7c67e501ca61f28e3e8c7ed495f60ceebe0bf

**Comment by AndroidDeveloperLB** [comment]
Well this was fast.

**Comment by AndroidDeveloperLB** [comment]
Did you also notice that when I set some app to be ignored, it doesn't remove it from the list of available updates?
