### ISSUE TITLE
Request: right in "updates" screen, allow to choose to ignore apps

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [rumboalla/apkupdater#281]
Including via multi-selection.

**Comment by quthla** [comment]
Yes, a button next to "Install" named "Ignore App" would be helpful

**Comment by AndroidDeveloperLB** [comment]
There is a limit of how many buttons you put. 
I was thinking of long pressing to switch to multi selection and be able to perform operations on those via the toolbar.
As for a single item-operation, you could have an overflow button.

**Comment by AndroidDeveloperLB** [comment]
There is a limit of how many buttons you put. 
I was thinking of long pressing to switch to multi selection and be able to perform operations on those via the toolbar.
As for a single item-operation, you could have an overflow button for the least used operations.

**Comment by quthla** [comment]
Can you link the docs in regards to the button limit?

**Comment by AndroidDeveloperLB** [comment]
What docs? I mean screen size limits. Of course you can add more and more buttons, but it just won't look well, and take more and more space.

**Comment by quthla** [comment]
Ah I see. But I think there's more than enough space left of install. And multi select just for ignoring the app with no other actions?

![Screenshot_20191214-122754](https://user-images.githubusercontent.com/30180109/70848137-52f0c200-1e6d-11ea-9c54-6e98459cff0d.jpg)

**Comment by AndroidDeveloperLB** [comment]
OK, how about both, then?
:)

**Comment by quthla** [comment]
Personally, I don't see a need for multi select when it's only for ignoring updates but in the end, it's @rumboalla who decides it 😊

**Comment by AndroidDeveloperLB** [comment]
Who said it's only for that?
You can also have "update" or "uninstall" or "share"...
As I said, less common operations.

**Comment by rumboalla** [comment]
https://github.com/rumboalla/apkupdater/discussions/393
