### ISSUE TITLE
Nagging Notification

### ISSUE THREAD

**Issue by time2moveon** [rumboalla/apkupdater#284]
Since the update notification is not persistent (can be swiped away/dismissed), why does it keep popping up (with notify sound) even though I have acknowledged (tapped the notification which opens the app)? It almost seems like it's caught in a loop, because the notification does dismiss after tapping it but once the app opens.. with the "update in progress" wheel showing and finishing... the notification appears again notifying of updates again w/ sound (annoying after awhile).
I also should mention that this only happens during the set update timeframe.. if out of that frame, I can open the app, it will look for updates and if found.. no notification pop-up.
Just seems a little bizarre how the whole update notification process works.

**Comment by rumboalla** [comment]
Fixed in f1e6f7af86bc426a2dd24d40a5b39e39a964ea21
