### ISSUE TITLE
Please remove the StartApp SDK

### ISSUE THREAD

**Issue by IzzySoft** [rumboalla/apkupdater#285]
I've noticed you've integrated the StartApp SDK again. May I kindly ask to remove that again? StartApp is known to be a specifically intrusive tracker and advertizer, harming the users' privacy (see e.g. [here](https://android.izzysoft.de/help?topic=modwarnings#startapp) for some details).

Thanks in advance!

**Comment by IzzySoft** [comment]
That's sad. Rules out your app for the privacy aware:

> StartApp can get quite intrusive: popups, search icon on your homescreen, [affecting the performance of your apps](https://blog.nimbledroid.com/2016/04/25/problems-with-libraries-and-sdks.html#Startapp)… And besides it [sends quite a few of your private data home to its makers](https://blog.choibean.com/2011/12/startapp-new-kind-of-scummy-advertising.html): IP, AndroidID, carrier, app details, device manufacturer, location, IMEI.

I won't nag anymore, just want you (and users of the app) to be aware of it. So if you insist on keeping it, please add at least a warning ("privacy statement") to the Readme. Thanks.

**Comment by rumboalla** [comment]
The SDK runs with minimum permissions (INTERNET) and only uses a small banner.
Privacy wise this app will never be privacy friendly since all sources except for F-Droid are going to track you.

**Comment by IzzySoft** [comment]
> The SDK runs with minimum permissions (INTERNET) and only uses a small banner.

Thanks, that's good to know! Though technically speaking: the SDK has access to everything the app integrating it has access to – which is a bit more than just the `INTERNET` permission (e.g. a list of all mobile/WiFi networks connected to, and whatever is available on external storage). With its not being open-source (to my knowledge), you cannot be sure what will be included.

> all sources except for F-Droid are going to track you.

True enough. Still, good to keep it as minimal as possible – which is why I raised this issue. But as I wrote: good to know you already "cut it down" and made sure it won't get too offending – thanks for that!

**Comment by unbranched** [comment]
@rumboalla 
Finding ads in an opensource project is so rare that everytime suprises me, so I'm here too.

> all sources except for F-Droid are going to track you.

This is not a reason to contribute with more tracking. With ads, profiling will become bigger with more and more third parties.

Also note that most users of your app are those who chose to stay away from GApps, maybe  trying to avoid tracking as much as they can. If you use ads it almost kills the purpose.

After all, do you really need the ads? I wonder how many money you make from them considering it's a semi-unknown app.
Just ask for donations instead.

I like the app and you deserve a thank, I contributed with translations.

**Comment by IzzySoft** [comment]
@rumboalla thanks for removing StartApp with v2.0.4 :green_heart:

**Comment by unbranched** [comment]
Many thanks! Really appreciated!
