### ISSUE TITLE
Request : add GitHub/GitLab updates

### ISSUE THREAD

**Issue by ld892012** [rumboalla/apkupdater#292]
Add possibility to add a GitHub or GitLab link for an app and the app automatically search for new versions for it (Newpipe or Bromite for example)

**Comment by sorryusernameisalreadytaken** [comment]
I nned this option too.

I would love to see that. I had a lot of apps I can just get from github or gitlab. I need to download the manually on my pc and then I sideload them. I hope for a better way to do this automaticly.

**Comment by EngineerGlitch** [comment]
Yes, nice request

**Comment by rumboalla** [comment]
It'd be great if someone could post a list of apps for this.

**Comment by DarkCrypt** [comment]
This is what you want.

Get Android app updates directly from the source -> [Obtainium](https://github.com/ImranR98/Obtainium)

**Comment by rumboalla** [comment]
> This is what you want.
> 
> Get Android app updates directly from the source -> [Obtainium](https://github.com/ImranR98/Obtainium)

You still have to add the apps manually there.
I was thinking about compiling a list and let ApkUpdater automatically check them.

Like this:
ApkUpdater - com.apkupdater - https://github.com/rumboalla/apkupdater/releases
NewPipe - org.schabi.newpipe - https://github.com/TeamNewPipe/NewPipe/releases

**Comment by DarkCrypt** [comment]
> You still have to add the apps manually there.

Correct, you do have to manually add the apps you want. Add one app at a time by URL or searching the supported sources in-app. Add multiple apps by importing from a URL list, from URLs in a file, GitHub starred repos, or searching supported sources in-app with the ability to multiple select.

> I was thinking about compiling a list and let ApkUpdater automatically check them.

Understood. This list is necessary for the GitHub (Self-Update) source in ApkUpdater correct?

**Comment by edgarchinchilla** [comment]
Please add a mechanism to support "app update sources", would be something like [WinGet Pkg Repository](https://github.com/microsoft/winget-pkgs/), where users were able to submit as many app update sources as they want.

**Comment by rumboalla** [comment]
https://github.com/rumboalla/apkupdater/discussions/395
