### ISSUE TITLE
Trying to "upgrade" to a lower version number?

### ISSUE THREAD

**Issue by famewolf** [rumboalla/apkupdater#293]
I've got several updates that appear where it appears to be trying to "upgrade" me to a lower version.  I've attached a screenshot with a few examples.  The oneplus icon packs are the issue here.
![Screenshot_20200105-130118](https://user-images.githubusercontent.com/4558832/71784036-c5604800-2fbc-11ea-8b75-6602b005c1b6.jpg)

**Comment by rumboalla** [comment]
Aptoide uses the versionCode to determine updates, so there's not much I can do here.

**Comment by famewolf** [comment]
I understand it uses the version code but why would the oneplus packages be going from version 2.0.3.xxxxx to 1.9.9.xxxx ?  Shouldn't an update ALWAYS be a higher number than current?
