### ISSUE TITLE
Reguest: Add option to *Skip* versions in the updates tab

### ISSUE THREAD

**Issue by time2moveon** [rumboalla/apkupdater#295]
This may have been touched upon regarding app releases. Both APKMirror and Aptoide post user uploaded versions ...ex. Adguard nightly's... which I don't want to install but they still show up in the "Updates Tab" even though I have checked *exclude "experimental" builds* in settings. I'd rather not "Ignore" apps in the apps list tab because I may miss an update that I really need. Hopefully a "skip" option can be added either through a button or pop-up sub-menu.

**Comment by sansnil** [comment]
+1

**Comment by rumboalla** [comment]
https://github.com/rumboalla/apkupdater/discussions/393
