### ISSUE TITLE
Download only option

### ISSUE THREAD

**Issue by 5x3** [rumboalla/apkupdater#298]
Please add apk download dir and ability to download only this updates to this dir, not install.
Also it will be great if you will keep apkmirror's apk names convention like apkmirror do, like:
com.google.android.apps.recorder_1.1.284933798-11000903_minAPI28(arm64-v8a)(nodpi)_apkmirror.com.apk
for all repos you use.

**Comment by rumboalla** [comment]
https://github.com/rumboalla/apkupdater/discussions/393
