### ISSUE TITLE
Oneplus Camera does not show up as an update for "Camera" on Oneplus 7 Pro

### ISSUE THREAD

**Issue by famewolf** [rumboalla/apkupdater#299]
The recent releases are here:  https://www.apkmirror.com/apk/oneplus-ltd/oneplus-camera/oneplus-camera-3-8-96-release/

Possible issue is on device the app just shows as "Camera" however manually downloading the latest version from that link did do an update to the existing app.

I was on v3.8.83 and it upgraded me to v3.8.96 which was released yesterday.  Timing issue?

**Comment by rumboalla** [comment]
Please provide more detailed information.
