### ISSUE TITLE
Uptodown don't show correct version in apkupdater

### ISSUE THREAD

**Issue by juanro49** [rumboalla/apkupdater#30]
Hi, I found a bug, uptodown don't show the correct upgradable version in many apps
![screenshot_20170228-135411](https://cloud.githubusercontent.com/assets/11600804/23406238/48c5f1ec-fdbe-11e6-95a4-90dbdb5afa46.png)
![screenshot_20170228-135443](https://cloud.githubusercontent.com/assets/11600804/23406253/527aa2dc-fdbe-11e6-8130-b72930e33459.png)

**Comment by rumboalla** [comment]
Already fixed. It will be included in next release.
