### ISSUE TITLE
cosmote apps fc when updated from apkupdater

### ISSUE THREAD

**Issue by patrickdrd** [rumboalla/apkupdater#300]
these two apps crash after updating with apkupdater,
it has happened twice already and on all 3 of my devices
(two phones and one tablet)..

https://play.google.com/store/apps/details?id=gr.cosmote.whatsup
https://play.google.com/store/apps/details?id=gr.cosmote.myaccount.widget

reproduce as following:
download a previous version from apkpure, e.g.:
https://apkpure.com/what-s-up/gr.cosmote.whatsup
(you can download 3.9.2 as well, 3.9.3 is the latest)
and then try to update it from apkupdater

also trying to extract the apk and install (after uninstalling) didn't work either..

**Comment by rumboalla** [comment]
Why is this an apkupdater problem? What install source are you using?

**Comment by patrickdrd** [comment]
I don't know/remember the source,
it looks like apkupdater installer (or downloader) issue to me,
because updating from playstore works fine,
I can't explain it otherwise..

**Comment by rumboalla** [comment]
Closing this one until more info is provided, it looks like a problem with the apk provided by the install source.

**Comment by patrickdrd** [comment]
I think there are some apps that cannot be installed or updated from an apk file but only from play store?
for example joey for Reddit, I tried to update it using an apk I extracted from another device (mine) but I ended up with a corrupt installation and that I should install again from play store etc
