### ISSUE TITLE
Downgrade protection

### ISSUE THREAD

**Issue by crisgithubcommit** [rumboalla/apkupdater#301]
![Screenshot_20200124-083529](https://user-images.githubusercontent.com/14579531/73049209-81a68300-3e84-11ea-8900-e4b3789f4316.jpg)

Hello,

Is it possible to prevent downgrades? I have some apps that have updates available but the update has a lower build than the one installed.

Thx a lot,

**Comment by rumboalla** [comment]
Aptoide uses the version code to determine updates.

**Comment by rumboalla** [comment]
Added this issue: https://github.com/rumboalla/apkupdater/issues/304
