### ISSUE TITLE
Add support for bundled APK installs

### ISSUE THREAD

**Issue by sansnil** [rumboalla/apkupdater#306]
I'm seeing more and more error -22's when trying to install APK's from Google Play. I'm assuming this is due to the new bundled APK format Google rolled out. Can support be added?

**Comment by patrickdrd** [comment]
I've just tried to install textra, 
it showed as installed but I got FC after install, I suppose because a bundle is needed to update it not just a single apk..

**Comment by rumboalla** [comment]
https://github.com/rumboalla/apkupdater/discussions/394
