### ISSUE TITLE
issue: apps cannot update

### ISSUE THREAD

**Issue by cherryglider** [rumboalla/apkupdater#307]
when i try to update apps that i didn't download from the play store, i get one of those errors: "app not found" or "install failed: -22" or "fragment: (long string of words and numbers)". this only happens to apps downloaded from external apks and not the play store, and this only started happening after i deleted apkupdater and re-downloaded it. it used to work before. may i have some help? if screenshots are needed let me know

**Comment by rumboalla** [comment]
Part of https://github.com/rumboalla/apkupdater/issues/306
