### ISSUE TITLE
apkmonk support - apkmonk.com

### ISSUE THREAD

**Issue by luxzg** [rumboalla/apkupdater#308]
Hi,

I stumbled on your app while looking for fixes to Huawei/Google situation.

Explanation:
- Huawei has new app "AppSearch" (AppSuche) that directs users without Google Services to alternative download sites
- list of download pages include APKPure, APKmirror and apkmonk
- your app nicely provides update functionality for the first two
- by adding apkmonk.com it would cover all sources that AppSearch currently uses

In short - please add https://www.apkmonk.com/ to supported sites in your app, that way future millions of Huawei users will be able to replace Google Play just by using 2 apps : AppSearch to find and install APKs, and your APKUpdater to keep them updated.

And thanks for nice app, bonus points for opensourcing and putting it to GitHub :) :+1:

**Comment by rumboalla** [comment]
https://github.com/rumboalla/apkupdater/issues/271
