### ISSUE TITLE
Unable to parse version

### ISSUE THREAD

**Issue by koroshiya** [rumboalla/apkupdater#31]
When checking for updates, the version name, rather than the version code, is being used.
Android has no forced convention for the version name, so when the code reaches executes VersionUtil.getStringVersionFromString, the app may throw an exception upon finding something unexpected.

I'm reproducing this right now looking for APKMirror updates for Tasker. The version name is 4.9u1, which causes getStringVersionFromString to fail to parse the version.

Instead, in the case of APKMirror, I recommend using the version code, which is always an integer, and a higher number can safely be considered a newer version.
This would mean grabbing the first line of text from the "appspec-value" class div, rather than the heading of the page, and grabbing the number between the brackets.

This might be better left until the APKMirror updates regarding pname and such have been implemented though. A reliable API would be nicer to parse than a web page (the structure of which may change).

**Comment by rumboalla** [comment]
Yes, the version parsing is a bit flaky and will fail against many strings.
I don't think it's worth making changes to this right now, since they will have the new API working soon.

**Comment by rumboalla** [comment]
I've made some changes that improve version parsing. It will now get versions from strings like NameV7, 23.45b8 and app-name-745-something.
