### ISSUE TITLE
get updates async error

### ISSUE THREAD

**Issue by Salman7236** [rumboalla/apkupdater#319]
Keeps checking for updates for 5-10 minutes then this error comes up: getupdates async error.

**Comment by mbnoimi** [comment]
Occurs since yesterday.
* Android 5.0
* Ver. 2.0.4 (42)

**Comment by Salman7236** [comment]
Reinstalling the app fixed the issue for me. I'll see if it happens again.

**Comment by mbnoimi** [comment]
> Reinstalling the app fixed the issue for me. I'll see if it happens again.

No, It worked by itself. This issue related to the remote repositories.
