### ISSUE TITLE
GetupdatesAsync Error

### ISSUE THREAD

**Issue by TheFly4242** [rumboalla/apkupdater#323]
Keep getting this error. Have uninstalled and reinstalled but no change. Only started as of yesterday.

**Comment by xianren78** [comment]
temporarily you can set off GooglePlay source

**Comment by TheFly4242** [comment]
That's the only one I use anyway usually.

**Comment by Bluscream** [comment]
Same here

**Comment by Eliminater74** [comment]
same here

**Comment by TheFly4242** [comment]
The problem seems to have resolved itself. Maybe Google had changed something their end and was reversed.

**Comment by keks24** [comment]
The issue seems to be appearing again.

It was working for me on the 04th December 2020.

**Comment by Deerp1976** [comment]
> The issue seems to be appearing again.
> 
> It was working for me on the 04th December 2020.

Same to me too. Think it's linked to APK Mirror.

**Comment by olucaslab** [comment]
It worked well yesterday, and now started again :/ 

(edit) Tested and turning off Google Play and APK Mirror it works 'normally'

**Comment by Deerp1976** [comment]
> It worked well yesterday, and now started again :/
> 
> (edit) Tested and turning off Google Play and APK Mirror it works 'normally'

Try taking off searching in Google Play Store for updates. APK Mirror and Aptoide are currently working.

**Comment by Pentaphon** [comment]
> Same to me too. Think it's linked to APK Mirror.

It works for me when I turn off Google Play. 

@rumboalla any comments on this?

**Comment by keks24** [comment]
I just did some updates today and `Google Play` seems to be working again.

I can only guess, that Google changed something with their API and then reverted these changes?
