### ISSUE TITLE
Is there an update source cdn that can be accessed in mainland China?

### ISSUE THREAD

**Issue by masx200** [rumboalla/apkupdater#324]
Is there an update source cdn that can be accessed in mainland China?

None of the four current update sources are accessible in mainland China.

**Comment by hemker** [comment]
@masx200 Do you know any update source that is indeed accessible?

**Comment by masx200** [comment]
> @masx200 Do you know any update source that is indeed accessible?

none

**Comment by rumboalla** [comment]
Please start a discussion here with more relevant info https://github.com/rumboalla/apkupdater/discussions
