### ISSUE TITLE
Inclusion to F-Droid

### ISSUE THREAD

**Issue by ghost** [rumboalla/apkupdater#33]
We at F-Droid received a packaging request for ApkUpdater. We already included the necessary build and metadata, but we failed at building it reproducible. This is a requirement if we want to re-use upstream binaries.

Right now we have two options: 

a) Continue to try to build reproducible
b) Don't care for reproducibility and sign with a f-droid specific key

The issue is, that the app will most likely try to update itself with official binaries, which will fail. So I'd like to discuss how to proceed and what you think is best suited.

**Comment by rumboalla** [comment]
Having builds with different signatures is going to be messy, 
I guess we should try to make the reproducible build pass. What can I do to help with that?

**Comment by krt16s** [comment]
@eighthave, does the buildserver publish diffoscope or something against upstream binaries? Or have I to do this manually?

**Comment by eighthave** [comment]
https://verification.f-droid.org tries to build everything on
f-droid.org, then runs diffoscope on it.  You can see build logs there
too in https://verification.f-droid.org/logs

**Comment by krt16s** [comment]
Uhm, this is for apps we have already build. I am talking about verifying against upstream releases

**Comment by eighthave** [comment]
If you mean like when using the `Binaries:` field, there isn't a diff
published as part of that workflow yet, but the plan is to publish
diffoscope output.  See fdroidserver#148

**Comment by eighthave** [comment]
oops, this is github, so here's the full link
https://gitlab.com/fdroid/fdroidserver/issues/148

**Comment by krt16s** [comment]
Looks like it only differs in the resources (and the signature of course). I uploaded a (partial) diffoscope out put to http://krt.marmaro.de/~krt/pub/com.apkupdater_9.apk.diff.html

@eighthave any crash-course information where those differences come from and how to easily minimize them?

**Comment by rumboalla** [comment]
They have been built with different gradle versions, that probably causes differences:
Created-​By:​·​Android·​Gradle·​2.​3.​0-​beta4 	3 	Created-​By:​·​Android·​Gradle·​2.​3.​0-​rc1

**Comment by eighthave** [comment]
it looks like you only have differences of unsigned vs signed, and a
build timestamp.  That won't affect the APK signature.

building with different gradle versions is unlikely to cause
differences, if so, that's a bug in gradle

**Comment by eMPee584** [comment]
[…] Just because the build log link hasn't been brought up yet:
https://f-droid.org/wiki/page/com.apkupdater/lastbuild_16

**Comment by rumboalla** [comment]
Is there any progress with this?

**Comment by jvschiavo** [comment]
Any progress?

**Comment by brundonsmith** [comment]
Any progress?
