### ISSUE TITLE
Get updates async error

### ISSUE THREAD

**Issue by Roby77ita** [rumboalla/apkupdater#330]
Hi, on oneplus 6t (android 10) with apkupdater 2.05 i get getupdatesasyncerror from some days

thank you

**Comment by Steltek** [comment]
Same issue here. 

Additional data: It only appears when Google Play is enabled in the Update Sources. When I disable that and leave APKMirror, Aptoide, and F-Droid, the update check works.

Digging further through the code, it seems to use http://auroraoss.com:8080 at some point. That server is not responding for me right now:

```
# telnet auroraoss.com 8080
Trying 146.59.157.181...

telnet: Unable to connect to remote host: Connection timed out
```

An alternative could be `http://auroraoss.in:8080` which is responding to HTTP requests. (Source: https://gitlab.com/AuroraOSS/AuroraStore/-/blob/master/app/src/main/java/com/aurora/store/TokenDispenserMirrors.java )

**Comment by Accipiter7** [comment]
Same Issue Here . After Disabling Google Play Everything Works Fine

**Comment by Accipiter7** [comment]
> Same issue here.
> 
> Additional data: It only appears when Google Play is enabled in the Update Sources. When I disable that and leave APKMirror, Aptoide, and F-Droid, the update check works.
> 
> Digging further through the code, it seems to use http://auroraoss.com:8080 at some point. That server is not responding for me right now:
> 
> ```
> # telnet auroraoss.com 8080
> Trying 146.59.157.181...
> 
> telnet: Unable to connect to remote host: Connection timed out
> ```
> 
> An alternative could be `http://auroraoss.in:8080` which is responding to HTTP requests. (Source: https://gitlab.com/AuroraOSS/AuroraStore/-/blob/master/app/src/main/java/com/aurora/store/TokenDispenserMirrors.java )

Tried This Solution [replaced .com with .in ] And It Worked

Thnx

**Comment by Roby77ita** [comment]
Yes i confirm removing play store as source worked 

Thank you

**Comment by bobel640** [comment]
> Same issue here.
> 
> Additional data: It only appears when Google Play is enabled in the Update Sources. When I disable that and leave APKMirror, Aptoide, and F-Droid, the update check works.
> 
> Digging further through the code, it seems to use http://auroraoss.com:8080 at some point. That server is not responding for me right now:
> 
> ```
> # telnet auroraoss.com 8080
> Trying 146.59.157.181...
> 
> telnet: Unable to connect to remote host: Connection timed out
> ```
> 
> An alternative could be `http://auroraoss.in:8080` which is responding to HTTP requests. (Source: https://gitlab.com/AuroraOSS/AuroraStore/-/blob/master/app/src/main/java/com/aurora/store/TokenDispenserMirrors.java )

it works, tnx

**Comment by EngineerGlitch** [comment]
The updates of all sources reworks, if no one has a problem close this issue

**Comment by Roby77ita** [comment]
Yes works perfectly

thank you

**Comment by j-ace-svg** [comment]
> Same issue here.
> 
> Additional data: It only appears when Google Play is enabled in the Update Sources. When I disable that and leave APKMirror, Aptoide, and F-Droid, the update check works.
> 
> Digging further through the code, it seems to use http://auroraoss.com:8080 at some point. That server is not responding for me right now:
> 
> ```
> # telnet auroraoss.com 8080
> Trying 146.59.157.181...
> 
> telnet: Unable to connect to remote host: Connection timed out
> ```
> 
> An alternative could be `http://auroraoss.in:8080` which is responding to HTTP requests. (Source: https://gitlab.com/AuroraOSS/AuroraStore/-/blob/master/app/src/main/java/com/aurora/store/TokenDispenserMirrors.java )

Where exactly in the repository are the references to auroraoss.com?

**Comment by hemker** [comment]
@j-ace-svg 
This url can be found in https://github.com/rumboalla/apkupdater/blob/2.x/app/src/main/java/com/apkupdater/repository/googleplay/GooglePlayRepository.kt#L26

**Comment by hemker** [comment]
@j-ace-svg Actually tried it with the provided alternative url, result is `Token dispenser error 521 Server error`, which makes sense as Cloudfare cannot reach the actual host. You can see the result by opening the url in your browser.

**Comment by Steltek** [comment]
You might need to run your own token dispenser as the public ones get overwhelmed very quickly now.
https://github.com/yeriomin/token-dispenser
