### ISSUE TITLE
APKUpdater's icon issue on Android TV

### ISSUE THREAD

**Issue by blackskull182** [rumboalla/apkupdater#331]
Hello,

the application icon on Android TV seems to be malformed:

https://ibb.co/jTzZ8T5
https://ibb.co/q1fk3CJ

Thanks

**Comment by CaioTheBrain** [comment]
Has this issue been solved? In which release?

**Comment by DarkCrypt** [comment]
[3.0.0-alpha-12](https://github.com/rumboalla/apkupdater/releases/tag/3.0.0-alpha-12)
