### ISSUE TITLE
ApkPure as source

### ISSUE THREAD

**Issue by hemker** [rumboalla/apkupdater#332]
Hey @rumboalla,
is there any reason why ApkPure was not initially included in version 2? If not, I'm going to port the ApkPure updater logic for this version!

Dennis

**Comment by EngineerGlitch** [comment]
Apkpure is not a reliable source in terms of APK, and we already have APKMirror which is more than enough, I advise you closing this issue

**Comment by hemker** [comment]
They also compare signatures against GooglePlay Store and exclude debug builds, so I think it is okay to use ApkPure. Furthermore, I provided a pull request to integrate it.
