### ISSUE TITLE
Updated apps broken on 4k Firestick

### ISSUE THREAD

**Issue by boardtc** [rumboalla/apkupdater#333]
I have some Irish TV catch up players apps side installed on my 4k Firestick and I wanted a way of updating them easily, I found this app which seems the ideal solution and installed the latest stable version.

I marked the apps installed by the firestick as ignore and updated my 2 TV player apps via the app. All appeared to go well, but when I went into the apps neither of them opened :-(

Is there something I should be aware of?

**Comment by rumboalla** [comment]
Please provide more information, like sources used, apps that caused problems, etc.

**Comment by boardtc** [comment]
Only certain version of these apps work for the firestick it seems, not necessarily the latest, so this app can't be used unfortunately :-(
