### ISSUE TITLE
Add check to also compare signature

### ISSUE THREAD

**Issue by m-rey** [rumboalla/apkupdater#337]
Normally, if an app update has a different signature, it's not straightforward to update using that apk without losing data.
Maybe a check could be implemented to also compares the signature fingerprint of the installed app with the fingerprint of its proposed update. It then should only appear as an update if they match. You may think that you'd need to download the update beforehand to read its signature fingerprint. However, some of the queried update sources also display the signature fingerprint of the update on its download page. Therefore, it could be scraped and used to only show updates with matching signatures, without having to download the update first.

I've also suggested this on the apkgrabber fork: https://github.com/hemker/apkgrabber/issues/83

**Comment by rumboalla** [comment]
This is already implemented for sources that allow this (Aptoide).
