### ISSUE TITLE
HTTP error fetching URL

### ISSUE THREAD

**Issue by ghost** [rumboalla/apkupdater#338]
This app is great at looking for updates. One thing is not so good is the search feature. Even the updates don't always download but that may be another issue. But when I do a search for an app I get an error message that pops up saying "HTTP error fetching URL" after I submit my search query.

**Comment by hemker** [comment]
Try disabling APKMirror as a source temporarily. The search api seems to be broken.

**Comment by ghost** [comment]
Thanks! The search went through this time.

On February 7, 2021 6:28:24 AM EST, Dennis Hemker <notifications@github.com> wrote:
>Try disabling APKMirror as a source temporarily. The search api seems
>to be broken.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/rumboalla/apkupdater/issues/338#issuecomment-774658032

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Don1250** [comment]
Hello it This Project alive???
