### ISSUE TITLE
checking for wrong variant of same app

### ISSUE THREAD

**Issue by gofirst2220** [rumboalla/apkupdater#34]
On my Samsung Galaxy S6, it checks for some system apps from HTC instead of Samsung. And some apps when updated with target version lower than system version, it will cause boot loops. Happened to me with ANT system apps on my S6.

**Comment by rumboalla** [comment]
Apps have the same pname so there's no much that can be done about it. 
Updating system apps can be dangerous and that's why they are excluded by default.
