### ISSUE TITLE
Request to specific (safe) repository within Aptoide 

### ISSUE THREAD

**Issue by santannamv** [rumboalla/apkupdater#343]
Since Aptoide does not have control over all applications listed on their several repositories, is it possible to fetch data only from the so called 'Apps' repository which is 99,99% trustful and manually curated?

**Comment by CaioTheBrain** [comment]
Add "tvapps" repo to that. It's the same as the regular one but for Android TV apps.

**Comment by peat80** [comment]
Would be great to (optionally?) fetch only those both repos. 
Curated sources would probably get app filtering working correctly for aptoid sources.

**Comment by rumboalla** [comment]
This is now implemented. Aptoide Source only uses apps and appstv stores.
