### ISSUE TITLE
A description of the application (sources that can allow it)

### ISSUE THREAD

**Issue by EngineerGlitch** [rumboalla/apkupdater#345]
@mezysinc @rumboalla, Add (for sources that can allow it), a description of the application

**Comment by hemker** [comment]
@GlitchGuy01 you mean for apks that are listed in the search tab? I think otherwise it would not make sense having a description for an application that is already installed on your phone.

**Comment by EngineerGlitch** [comment]
> @GlitchGuy01 you mean for apks that are listed in the search tab? I think otherwise it would not make sense having a description for an application that is already installed on your phone.

@hemker Yes, apks listed when you search

**Comment by rumboalla** [comment]
https://github.com/rumboalla/apkupdater/discussions/393
