### ISSUE TITLE
Suggestion: hide specific updates, but not the entire app

### ISSUE THREAD

**Issue by i-am-ecc** [rumboalla/apkupdater#348]
I've been using APKUpdater for a long time, so I can get updates ahead of the official Google Play Store ones. It works fine, but I'd like to give a suggestion, as below.
APKUpdater can hide apps that you don't want to update. That's OK. But what if I just want to hide a specific update, but still wait for the next ones? That'd work in cases of, in example, an incompatible update in the list (talk about Kindle 14.x over Kindle 8.x, in example - it doesn't work; or Amazon Music 16.x over 17.x - it doesn't work either). In other words: it could have a "ignore this update" feature, while still allowing to wait for the next ones. In its current state, if I hit "Ignore" on an app, APKPure will never update it again.
Is there any chance for something like that?

**Comment by rumboalla** [comment]
duplicate #295
