### ISSUE TITLE
getUpdateAsync error

### ISSUE THREAD

**Issue by eldair** [rumboalla/apkupdater#350]
Hello,
I keep gettint getUpdateAsync error in updates tab for the past couple of days.

**Comment by HoneyBadgerSeeker** [comment]
Hello, me too, I can't refresh/search for apk/update.

**Comment by keks24** [comment]
I am also having this issue on my `OnePlus One (LineageOS 17.1 20210318-NIGHTLY-bacon)`.

This seems to be a server issue.

@rumboalla Maybe the error message could be more obvious, so people do not complain all the time...

---

This also relates to:
* #330
* #319
* #313

**Comment by eldair** [comment]
Disabling google play source fixes the issue (as found in issues @keks24 linked).
