### ISSUE TITLE
GetUpdatesSync error

### ISSUE THREAD

**Issue by phabyoautrey** [rumboalla/apkupdater#353]
GetUpdatesSync error

**Comment by dfg369853** [comment]
Disable Google play in settings apkupdater. Aurora Dispencers is down!

**Comment by hl2guide** [comment]
> 
> 
> Disable Google play in settings apkupdater. Aurora Dispencers is down!

Thanks nice fix.

**Comment by TPS** [comment]
AuroraStore has had another complete overhaul recently.  Maybe that's the reason?

**Comment by dfg369853** [comment]
> AuroraStore has had another complete overhaul recently.  Maybe that's the reason?

No, reason in down old Aurora Dispencers

**Comment by DavidBurela** [comment]
It seems that once an error is thrown with one repo, then all update searches stop. But once you disable a broken repo then results for the others will work.

Seems we need to add some error handling, to gracefully handle a single broken app repository.

**Comment by Olf0** [comment]
This seems to be a duplicate of issue #351.
Although @DavidBurela's [comment does add a new aspect](https://github.com/rumboalla/apkupdater/issues/353#issuecomment-821962809):
The lack of proper error reporting and handling makes it hard to comprehend, that only a single repository fails, and the issue can be resolved by disabling that single repository.
