### ISSUE TITLE
Enchancement suggestion: Progress bar under apps during updates

### ISSUE THREAD

**Issue by eddie-LA** [rumboalla/apkupdater#356]
First, great work! This app is a boon to older less powerful phones without Google apps! That said, I have a couple of suggestions...

When I found this app I have found myself on edge at times when I update apps. I don't know how big the update is and sometimes it takes a while and I wonder if the app still works. This lead to a few exits, surprises and misclicks.

Suggest adding a progress bar under apps that are currently updating. Optionally, the progress bar could be tied to a notification (ala Play Store style) so the user knows exactly when the update will be done even if they exit the app.

**Comment by rumboalla** [comment]
https://github.com/rumboalla/apkupdater/discussions/393
