### ISSUE TITLE
Add option to download directly from play using googleplaycrawler

### ISSUE THREAD

**Issue by rancidfrog** [rumboalla/apkupdater#36]
It would be great to be able to download directly from play store, instead of going through and relying on 3rd party sites.
Google Play Crawler allows one to download apps from play store directly, example Raccoon: https://github.com/onyxbits/Raccoon/tree/master/src/main/java/com/akdeniz/googleplaycrawler

It works great on desktop using java-api, which should be adaptable for android app.
User will need to use google account, preferrably dummy account not tied to personal account

- https://github.com/onyxbits/Raccoon
- https://github.com/Akdeniz/google-play-crawler
- https://github.com/onyxbits/raccoon4/tree/master/src/main/java/com/akdeniz/googleplaycrawler

**Comment by rumboalla** [comment]
This a duplicate. Please post this in the same issue: https://github.com/rumboalla/apkupdater/issues/19
