### ISSUE TITLE
Synchronising fails for F-Droid and Google Play

### ISSUE THREAD

**Issue by Olf0** [rumboalla/apkupdater#365]
### Observation
Synchronising repositories (by pulling down from the top) fails for F-Droid and Google Play (i.e. only APKMirror and Aptoide are working).
The displayed errors are different for F-Droid and for Google Play:
1. F-Droid (see also first screenshot below)
   `updateAsync: data is null`   [CLOSE]   
2. Google Play (see also second screenshot below)
   `s/i0/i/f`   [CLOSE]

This was tested with only a single repository enabled at a time, because [the lack of proper error reporting and handling makes it hard to comprehend, which repository fails](https://github.com/rumboalla/apkupdater/issues/353#issuecomment-821962809).

#### Software versions
Tested with APKUpdater 2.0.4 and 2.0.5 on AOSP 4.4.4 ("Kitkat", API level 19).
Note: This is on an AOSP branch (like LineageOS etc.) without Google Play Services, OpenGapps or microG installed.

#### Notes
At first sight, I assumed this to be a duplicate of issue #351, but then I realised that the error message and the affected repositories do differ!
- "`getUpdatesAsync error.`" for Google Play in issue 351, versus "`s/i0/i/f`" for Google Play here.
- "`updateAsync: data is null`" for F-Droid here (versus "`getUpdatesAsync error.`" for Google Play in issue 351).

Unfortunately nobody reported APKUpdater's and Android's version with which issue #351 (plus the duplicate issue #353 and issue #364) were observed.

#### Screenshots
- Screenshot 1 (for F-Droid failing to synchronise per APKUpdater 2.0.5)
![Screenshot_20210906_001](https://user-images.githubusercontent.com/16547876/132147410-3176ddb7-5de6-4a30-8308-5bf598ff621d.png)

- Screenshot 2 (for Google Play failing to synchronise per APKUpdater 2.0.5)
![Screenshot_20210906_002](https://user-images.githubusercontent.com/16547876/132147426-12dd7202-d753-4477-be6e-bccf4c27f236.png)

**Comment by gnpaone** [comment]
> Unfortunately nobody reported APKUpdater's and Android's version with which issue #351 (plus the duplicate issue #353 and issue #364) were observed.

#364 I am using Android 11 (same problem in Android 10) and APKUpdater v2.0.5. Turning off Google Play store option in settings worked for now upto some extent but I hope this issue get fixed soon cuz I have some apps for which I need playstore updates via this app. (Playstore version is latest too)

**Comment by Olf0** [comment]
@gnpaone, thank you for reporting the environment, in which you observed issue #364, but this still is a duplicate of issue #351!
As I clearly stated in the section "**Notes**" above, this issue (#365) is a slightly different one (with different error messages etc.). 
Thus please close issue #364, and re-post your above comment at issue #351 (maybe also attach your screenshots there, because there are none yet).

**Comment by LinusSch** [comment]
Using APKUpdater v2.0.5 on Android 8.0.0, with Play Services and F-droid installed: F-droid is working but for Play store I get "getUpdatesAsync error."

**Comment by MarieQuemart17** [comment]
Bonjour,
J'ai un peu le même soucis, problème de synchronisation avec le Playstore malheureusement besoin de faire des mises à jour sur celui-ci. 
Si quelqu'un aurait la solution svp 😊
Je mets
![Screenshot_2022-02-01-15-14-41-898_com apkupdater](https://user-images.githubusercontent.com/98825240/151984939-c424d5b5-e6c8-4411-a124-2dc2626e98be.jpg)
 la capture d'écran

**Comment by Olf0** [comment]
> Si quelqu'un aurait la solution svp

Well, though it makes no difference in this specific case, you should read first:
- This is the wrong issue thread, [as already denoted](https://github.com/rumboalla/apkupdater/issues/365#issue-988650136) in the issue description.
  Your issue likely is #351, if you read properly.
- As most people here, you miss to describe your environment: Device, Android version etc.
  Such reports are not really helpful, especially when accompanied with a huge screenshot, which lacks any new information.
