### ISSUE TITLE
Making downloads effortless like from Aptoide? 

### ISSUE THREAD

**Issue by ghost** [rumboalla/apkupdater#366]
Would it be possible to update applications with one click from ApkMirror instead of doing it manually by going to their site?
Would be good if it looked like updating from Aptoide. With one click.

**Comment by TPS** [comment]
See https://github.com/rumboalla/apkupdater/issues/16.  APKMirror doesn't allow this.

**Comment by ghost** [comment]
> See #16. APKMirror doesn't allow this.

Thanks!
