### ISSUE TITLE
Screen reader accessibility enhance needed

### ISSUE THREAD

**Issue by CiprianDinca9** [rumboalla/apkupdater#370]
For the blind people, it is not clear from what source we download. Here is what my screen reader read for an app: App Icon,   
Discord-Canary,   
com.discord,   
109.0 - Alpha (109200) -> 110.1 - Alpha (110201),   
Source Icon. No source name, as you see. Also try, if possible, to fix these issues other users here on GitHub opened. I thought not to mention them myself because you can see them if you see this one. Thank you!

**Comment by TPS** [comment]
[Google's Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor) might be useful to help solve this.
