### ISSUE TITLE
GetUpdatesAsync error.

### ISSUE THREAD

**Issue by MarieQuemart17** [rumboalla/apkupdater#372]
Bonjour,
Je voudrais les Maj du Google Playstore malheureusement ça ne fonctionne pas et le message d'erreur est celui du titre du post.

Je met également la capture d'écran.

Si quelqu'un pouvais m'aiguiller afin de savoir si le soucis peut être régler svp.

Merci d'avance 😊

**Comment by hehedemuse** [comment]
I have the same problem.

**Comment by ckesc** [comment]
Looks like duplicate of #351

**Comment by killerrook** [comment]
Same problem on colorOS v6.0 (Android 9) Device OPPO Realme 1 CPH1861
![Screenshot_2022-10-15-07-01-29-05_3bb3bffa89a9f6c4fe870b0aa2a0ce96](https://user-images.githubusercontent.com/28833686/195963169-da41c845-160d-4e40-b8b3-d1ea6e3af55d.png)

**Comment by PeterKW** [comment]
https://apt.izzysoft.de/fdroid/index/apk/de.apkgrabber
https://github.com/hemker/apkgrabber

**Comment by IRainman** [comment]
> https://apt.izzysoft.de/fdroid/index/apk/de.apkgrabber https://github.com/hemker/apkgrabber

Thank you

**Comment by StormProductionsMusic** [comment]
> > https://apt.izzysoft.de/fdroid/index/apk/de.apkgrabber https://github.com/hemker/apkgrabber
> 
> Thank you

Pretty old too, any new apps that help update APKs?

**Comment by PeterKW** [comment]
> Reference

I've forked it but I've been busy to get started on updating code but happy to review any pull requests? https://github.com/PeterKW/apkgetter

**Comment by StormProductionsMusic** [comment]
Good one, though please compile it and release it too, for people like me that don't know how to compile apps. :)
