### ISSUE TITLE
up

### ISSUE THREAD

**Issue by kolf1234** [rumboalla/apkupdater#377]

**Comment by PeterKW** [comment]
https://apt.izzysoft.de/fdroid/index/apk/de.apkgrabber
https://github.com/hemker/apkgrabber

**Comment by Elite911** [comment]
> https://apt.izzysoft.de/fdroid/index/apk/de.apkgrabber https://github.com/hemker/apkgrabber

That's been abandoned per hemkers post here: https://github.com/hemker/apkgrabber/issues/100#issuecomment-1467612510
