### ISSUE TITLE
Token dispenser erroe

### ISSUE THREAD

**Issue by AlexKalopsia** [rumboalla/apkupdater#380]
As soon as I start the app I get the following error:

`Token dispenser resturned an auth error for http://auroraoss.com:8080/email`

This seemingly prevents any app from being updated

**Comment by naruhenix** [comment]
I get the same error sadly

**Comment by CtodGit** [comment]
Same here too from fire hd8 2022 release

**Comment by TPS** [comment]
Hang on, there's major rewrite in the works, but might take a while.

**Comment by CtodGit** [comment]
> Hang on, there's major rewrite in the works, but might take a while.

Awesome to hear that. Looking forward to it.
