### ISSUE TITLE
v3.0.0-α-01 doesn't update?

### ISSUE THREAD

**Issue by TPS** [rumboalla/apkupdater#382]
@rumboalla Just tried your new α release.  It looks good (other than the lack of the app icon & missing settings), but doesn't seem to update @ all.  Does that match what you expect?  If there were a running changelog, I'd check there 1st, but couldn't find 1.

**Comment by peat80** [comment]
You know what alpha software is? 🤔😀

Anyways, the new ui looks promising. Can't wait to see a useable version arriving. 👍
Only the icon size is way too big. On the phone there should be at least 3 icons per row, and on tv 5. 😎

**Comment by maj113** [comment]
> Only the icon size is way too big.

Hopefully we get an older style list view too

**Comment by Don1250** [comment]
i like the new UI but the icon size is way too big, i will waiting for update?!?!?!?!?!?

**Comment by SUNNY-220Fi** [comment]
Can anyone send link for I phone…..

**Comment by maj113** [comment]
> Can anyone send link for I phone…..

What? There is no build for iPhone

**Comment by TPS** [comment]
Closed completed & all future feedback should go to #383
