### ISSUE TITLE
3.x Alpha Feedback

### ISSUE THREAD

**Issue by rumboalla** [rumboalla/apkupdater#383]
Post your feedback here.

**Comment by hirenshah** [comment]
Firstly, having this app being developed further is amazing news. I had to double and triple check that I was reading the notifications correctly lol. Thank you very much.

Now down to business:

1) With this being an alpha, things are obviously WIP. Are you able to share details around what has been completed, is work in progress, and still outstanding?

2) I'm asking the above because the Updates tab seems to be an endless "in progress" animation, and I have no idea if that is to be expected or an issue:

https://github.com/rumboalla/apkupdater/assets/418112/e5cb8c9c-03c1-4b2e-abd9-7bbad7b283d3

3) Knowing the above would also help reduce the number of issues / feature requests being raised. I say "reduce" because no matter how much information you provide, there are always going to be people who don't bother reading... some will though. 

4) What are the number values towards the left of app icons?

https://github.com/rumboalla/apkupdater/assets/418112/6890f692-b854-40a4-a857-e0f61d108be8

5) When the number of columns is increased, I don't think the left to right bouncing of the package name is helpful, especially when a single tap results in it stopping for just that app. Having it static and left aligned by default would be better, and then users could scroll left and right should they wish to. You could then have a long press copy the value to clipboard.

6) I do have more thoughts/suggestions, but it would be a waste of both of our time when I don't know what I mentioned in 1).

**Comment by rumboalla** [comment]
> 2. I'm asking the above because the Updates tab seems to be an endless "in progress" animation, and I have no idea if that is to be expected or an issue:
> 

There was a bug when checking more than 100 apps, it's fixed now.

**Comment by hirenshah** [comment]
I can confirm that the Updates tab is loading now 👍

Are you able to share what is still pending, answer what the numbers to the left of each app icon are, and comment on that bouncing text (that is really making my eyes hurt). 


Other things I've noticed:

1) I would expect to swipe down to refresh on the Updates tab

2) Filte between User, System and All apps on the Updates tab

3) Option to choose stable va beta updates

4) Option to ignore certain apps

**Comment by hirenshah** [comment]
More things I've noticed:

5) Filtering Apps tab by System, User and All only applies the  same filter to the Updates tab when the app is closed and reopened.

6) Some of the updates being shown are for Android TV - Disney+ and F1 TV are two examples

**Comment by maj113** [comment]
Okay so couple things

 - A list view (like it was in 2.x) would be nice to have
 - Apps that can be updated should show the old version too
 - One thing I have noticed that under the `apps` tab it struggles to load the icons when scrolling on a high end phone
 - On icon view I'd move the version string to the place where the full app/apk name is (com.android.....) and hide the apk name entirely, maybe something like a hold to show more info


Currently the UI feels cluttered, there's too much info clumped together and too many different looking elements together (version bubble looks out of place)

**Comment by TPS** [comment]
A fix for 2.𝓍's keeping APKs in cache (though successfully installed) would also be appreciated.

**Comment by peat80** [comment]
Hopefully this new version will also get support for android tv at some point. 😀

The ui upgrade looks really nice. 😎👌

**Comment by Don1250** [comment]
https://github.com/rumboalla/apkupdater/assets/111435312/bc46abb6-fb95-40dc-a7d8-74f22d9b015b
please add the ignore button on update tab without going all app tab also please fix above update i am on android 11 i am getting app Update of android 12 and WearOS And Android Tv on Phone

**Comment by mindtrapper** [comment]
Welcome back!

1. Please add option to ignore only current version instead of a whole app
2. Add a check to not show Wear OS updates.

Thank you!

**Comment by Saloframes** [comment]
A list view with smaller icons would be a lot easier on the eyes.

**Comment by hirenshah** [comment]
Additional Items:

- I've updated to alpha-07 but it continues to show an available update for APK Updater.

- I have the latest version of the F1 TV app on my phone, but APK Updater shows an available update. Tapping on the download icon takes me to the Android TV version of the F1 TV app.

- Google Wallet update takes me to the APKMirror page for the Wear OS version. 

- Any comments on the other things I had mentioned?

**Comment by dfg369853** [comment]
Add Russian Language in stable 3.0.0? Need help in translate?

**Comment by maj113** [comment]
> A list view with smaller icons would be a lot easier on the eyes.

I second this, been asking for it too

**Comment by Don1250** [comment]
New App Icon please the one you pick don't like it!!!

https://www.flaticon.com/free-icon/desktop_2807222

**Comment by maj113** [comment]
> New App Icon please the one you pick don't like it!!!

I honestly prefer the one Apkupdater has now over whatever that is

**Comment by hirenshah** [comment]
> New App Icon please the one you pick don't like it!!!
> 
> https://www.flaticon.com/free-icon/desktop_2807222

Icons are very much a personal preference. Most launchers allow you to set your own, so your best bet is to do just that.

**Comment by shadypt** [comment]
It would be nice to have information on what version do you have installed and what is the lastest version.
Something like apkgrabber does.
Thanks for the amazing app.

**Comment by mindtrapper** [comment]
Thanks for filtering for wear os. My next suggestion is to add an option to check for disabled apps also.

**Comment by KotaruProject** [comment]
Application crashed in my Android 13 rom(
Last version alpha from github.

**Comment by rumboalla** [comment]
> New App Icon please the one you pick don't like it!!!
> 
> https://www.flaticon.com/free-icon/desktop_2807222

New icon proposals are welcome, but they need to be adaptive vector icons.
More info: https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**Comment by rumboalla** [comment]
> Application crashed in my Android 13 rom( Last version alpha from github.

Logs please.

**Comment by rumboalla** [comment]
> Add Russian Language in stable 3.0.0? Need help in translate?

It's a bit early for translation but any pull request with translations is welcome.

**Comment by KotaruDev** [comment]
> > Application crashed in my Android 13 rom( Last version alpha from github.
> 
> Logs please.

https://logpaste.com/09wnRkQ4

**Comment by shadypt** [comment]
An option to choose in wich screen the app opens would be nice.
The app starts on the installed apps but for me I just want the section of the updates.
Another thing is that the beta updates available should be identified as such.
Also the version that is installed and the version that is the latest, like I referred a few comments above.
Similar to what apkgrabber does.

**Comment by du33169** [comment]
extra '/' in the link to apkmirror

![Screenshot_20230731_000339.jpg](https://github.com/rumboalla/apkupdater/assets/46591250/6b68cde0-7bbf-4768-8e41-5be1dd356872)

**Comment by peat80** [comment]
The new ui for tv looks and works great. 😎👌
Would be nice to have a switch in the settings to manually enable the dark mode to use it on tv too. 🤔

And if possible a better filter for tv apps, or if not possible a ignore update button. There are a lot app updates shown on tv that are phone versions.

Anyways, great job with all the updates for this lovely app lately. 👌👌👌

**Comment by rumboalla** [comment]
> The new ui for tv looks and works great. 😎👌 Would be nice to have a switch in the settings to manually enable the dark mode to use it on tv too. 🤔
> 
> And if possible a better filter for tv apps, or if not possible a ignore update button. There are a lot app updates shown on tv that are phone versions.
> 
> Anyways, great job with all the updates for this lovely app lately. 👌👌👌

Last version has some small changes that should make APKMirror updates better on Android TV.
The theme setting and ignore version are on my TODO for things to do after the first 3.0 release.

**Comment by AnonymousWP** [comment]
Thanks for this great rework of the app! I've been using your 2.x.x version since many years. Some suggestions:

- Bring back the parent version and target version (just like with 2.x.x)
- When enabling Aptoide, it does not ignore betas. Ignoring betas only (?) works when using APKMirror and GitHub as update source
- For some reason, 2.x.x is able to detect that there's an update available for app X and Y, while on 3.x.x it's not shown

> extra '/' in the link to apkmirror
> 
> ![Screenshot_20230731_000339.jpg](https://user-images.githubusercontent.com/46591250/257062259-6b68cde0-7bbf-4768-8e41-5be1dd356872.jpg)

Yeah, I also noticed this, but it doesn't really matter; browsers automatically remove the extra forward slash, but does make the process slower.

**Comment by AnonymousWP** [comment]
> extra '/' in the link to apkmirror
> 
> ![Screenshot_20230731_000339.jpg](https://user-images.githubusercontent.com/46591250/257062259-6b68cde0-7bbf-4768-8e41-5be1dd356872.jpg)

Yeah, I also noticed this, but it doesn't really matter; browsers automatically remove the extra forward slash, but does make the process slower.

**Comment by peat80** [comment]
I like to translate the app into german.
Should i start yet or wait until a stable release is in sight?

**Comment by AnonymousWP** [comment]
I'll start the translation of Dutch soon and open a PR. :)

**Comment by rumboalla** [comment]
> Thanks for this great rework of the app! I've been using your 2.x.x version since many years. Some suggestions:
> 
> * Bring back the parent version and target version (just like with 2.x.x)

Yes, this will eventually come back along the What's new if available

> * When enabling Aptoide, it does not ignore betas. Ignoring betas only (?) works when using APKMirror and GitHub as update source

It should, the ignore tags are being sent when making the requests. Do you have an example?

> * For some reason, 2.x.x is able to detect that there's an update available for app X and Y, while on 3.x.x it's not shown
> 
> > extra '/' in the link to apkmirror
> 
> Yeah, I also noticed this, but it doesn't really matter; browsers automatically remove the extra forward slash, but does make the process slower.

The double slash is already fixed 


> I like to translate the app into german. Should i start yet or wait until a stable release is in sight?

> I'll start the translation of Dutch soon and open a PR. :)

I think it's ok to start with translations

**Comment by AnonymousWP** [comment]
> It should, the ignore tags are being sent when making the requests. Do you have an example?

Yes, because when I enable Aptoide as update source and I click one of the apps (that with only APKMirror weren't found), it showed me Nova Launcher 8.0.6, which is a beta (according to their Discord server).

**Comment by Don1250** [comment]
can you add apkpure source like getting update from APKpure or also install apps, game from search bar in ApkUpdater?

**Comment by Stanzilla** [comment]
> Okay so couple things
> 
>  - A list view (like it was in 2.x) would be nice to have
>  - Apps that can be updated should show the old version too
>  - One thing I have noticed that under the `apps` tab it struggles to load the icons when scrolling on a high end phone
>  - On icon view I'd move the version string to the place where the full app/apk name is (com.android.....) and hide the apk name entirely, maybe something like a hold to show more info
> 
> 
> Currently the UI feels cluttered, there's too much info clumped together and too many different looking elements together (version bubble looks out of place)

Agree with all of this, otherwise amazing work! I personally like the icon of V2 better but as you said, opinions.

**Comment by AnonymousWP** [comment]
Another suggestion I have is to remove one of the two refresh-icons that are displayed when the Updates tab is being refreshed. It's redundant and doesn't look too good. Choose either.

**Comment by KotaruDev** [comment]
Please show the version number of the app when updating, and also make the icons a little smaller, they are too big at the moment

**Comment by hirenshah** [comment]
If I show system apps, it shows versions for Android 14. I have a Samsung S23 Ultra which is on A13 and therefore the updates shown aren't actually compatible.

**Comment by rumboalla** [comment]
Moving this here https://github.com/rumboalla/apkupdater/discussions/396
