### ISSUE TITLE
Latest versions broke screen reader usage

### ISSUE THREAD

**Issue by CiprianDinca9** [rumboalla/apkupdater#384]
The latest alpha versions are hard to operate with screen readers. Please label icons, label app sources because it just speaks source icon. And more.

**Comment by TPS** [comment]
@rumboalla [Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor) is a tool that may be useful.

**Comment by rumboalla** [comment]
I get this when clicking source icons: "APK Mirror Image", "F Droid Image" and "Github Image"

**Comment by CiprianDinca9** [comment]
So that is with a screen reader? Are you using Google TalkBack for this?

**Comment by rumboalla** [comment]
> So that is with a screen reader? Are you using Google TalkBack for this?

Yes with TalkBack.
In any case, an additional List/AndroidTV UI (like the one in 2.x) is coming soon, and it should be much easier to navigate with a reader.
![Screenshot_220230729_151124](https://github.com/rumboalla/apkupdater/assets/21153554/9d5418c8-534c-4b56-b689-ec40fa91fcba)

**Comment by CiprianDinca9** [comment]
I see. Also, can you reimplement root install? I didn't seem to find it in the settings.

**Comment by rumboalla** [comment]
> I see. Also, can you reimplement root install? I didn't seem to find it in the settings.

Eventually, yes.
