### ISSUE TITLE
Problem with Galaxy Note 9 

### ISSUE THREAD

**Issue by aaref1234** [rumboalla/apkupdater#390]
Hi .

There is a problem in the Galaxy Note 9 (Android 10), which is when opening the app, the System UI hangs, as well as the Tasker app .

This problem exists in alpha and beta versions .

**Comment by rumboalla** [comment]
Logs please

**Comment by aaref1234** [comment]
![logcat_٠٨-٠٨-٢٠٢٣_٠١-٢٤-٤٤.txt](https://github.com/rumboalla/apkupdater/files/12285586/logcat_.-.-._.-.-.txt)

**Comment by rumboalla** [comment]
It looks like Samsung GameManagerService may be interfering somehow with the app, but it's hard to say.

**Comment by rumboalla** [comment]
Closing because this doesn't seem to be an app issue.

**Comment by aaref1234** [comment]
The problem is not caused by Samsung Game Services .

The problem is with the interface layout in the app .

If you choose the TV layout, this problem disappears .
