### ISSUE TITLE
APKUpdater Romanian Translation

### ISSUE THREAD

**Issue by StormProductionsMusic** [rumboalla/apkupdater#391]
Hi,

Just translated latest strings.xml for the APKUpdater app to Romanian. Click [here](https://github.com/rumboalla/apkupdater/files/12283775/values-ro.zip) to download and enjoy!

P.S: Please let me know what's the easiest method to check when new strings are being added. I'm new to GitHub (I"ve previously translated only files that were being sent directly to me) so that I could translate them before the update goes public. This would ensure that people who are using the language would get the new features imediately translated. Thanks!

**Comment by rumboalla** [comment]
> Hi,
> 
> Just translated latest strings.xml for the APKUpdater app to Romanian. Click [here](https://github.com/rumboalla/apkupdater/files/12283775/values-ro.zip) to download and enjoy!
> 
> P.S: Please let me know what's the easiest method to check when new strings are being added. I'm new to GitHub (I"ve previously translated only files that were being sent directly to me) so that I could translate them before the update goes public. This would ensure that people who are using the language would get the new features imediately translated. Thanks!

Thanks, for the translation. It's added now https://github.com/rumboalla/apkupdater/commit/aa805e9a12b8dc7f193d60670bb2b9513aca088f

You can watch the repo to get notifications to keep track of what's changed.

**Comment by rumboalla** [comment]
@StormProductionsMusic 
I'm getting this error with the translation. Looks like it missing one plural
```
<plurals name="notification_update_description">
        <item quantity="few">MISSING</item>
        <item quantity="zero">Nicio actualizare găsită.</item>
        <item quantity="one">A fost găsită %1$d actualizare.</item>
        <item quantity="other">Au fost găsite %1$d actualizări.</item>
    </plurals>
```
```
/home/runner/work/apkupdater/apkupdater/app/src/main/res/values-ro/strings.xml:48: Error: For locale "ro" (Romanian) the following quantity should also be defined: few (e.g. "2 zile") [MissingQuantity]
    <plurals name="notification_update_description">
    ^

   Explanation for issues of type "MissingQuantity":
   Different languages have different rules for grammatical agreement with
   quantity. In English, for example, the quantity 1 is a special case. We
   write "1 book", but for any other quantity we'd write "n books". This
   distinction between singular and plural is very common, but other languages
   make finer distinctions.

   This lint check looks at each translation of a <plural> and makes sure that
   all the quantity strings considered by the given language are provided by
   this translation.

   For example, an English translation must provide a string for
   quantity="one". Similarly, a Czech translation must provide a string for
   quantity="few".

   https://developer.android.com/guide/topics/resources/string-resource.html#Plurals
```

**Comment by StormProductionsMusic** [comment]
The string you're looking for is ”Câteva”, which in English is ”Few”. 
Sorry for missing that one.

**Comment by rumboalla** [comment]
> The string you're looking for is ”Câteva”, which in English is ”Few”. Sorry for missing that one.

It's not "few" that needs translating, it's few for the plural of updates found. Can we use the same string for "other" in this case?

**Comment by StormProductionsMusic** [comment]
> It's not "few" that needs translating, it's few for the plural of updates found. Can we use the same string for "other" in this case?

Sure, the translation for "other" would be "altele", so feel free to use that.
