### ISSUE TITLE
Support unattended background updates

### ISSUE THREAD

**Issue by matchboxbananasynergy** [rumboalla/apkupdater#397]
Hey there! I just found out about this app and it looks interesting.

Since the app targets Android 14 (API 34), it should be possible to use the Android 12+ unattended updates API in order to update apps without user interaction. For people who are using Android 11 and below, they could still benefit from the notification system instead.

This is something that a similar app to yours called Obtainium has struggled to implement for a long time now (https://github.com/ImranR98/Obtainium/issues/25) but that's due to it being a Flutter app and the plugins for that API not working properly.

As your app is written in Kotlin, this should be fairly easy to implement, and a lot of other apps written in Kotlin already do it.

~~To do this, you'll need to use the `UPDATE_PACKAGES_WITHOUT_USER_ACTION` permission. Of course, there's likely more you'll have to do to get this working, but it's something to consider. :)~~

I can actually see that this is already in the manifest (https://github.com/rumboalla/apkupdater/blob/3.x/app/src/main/AndroidManifest.xml#L13C58-L13C58). Does that mean that people on Android 12 can expect unattended updates as long as APKUpdater is the installer of record for a given app?

**Comment by TPS** [comment]
No-interaction auto-update is now _possible_ (I've 1 app — [FFUpdater](https://github.com/Tobi823/ffupdater/commit/f10d54cefd9f334f6499c47667f6cf4ff0a41431) — that implements it flawlessly), but very tight parameters must be met, most notably targetting _Android 10+_.  See some details @  https://www.xda-developers.com/android-12-alternative-app-stores-update-apps-background/.  It's _not_ just the 1 declaration.

**Comment by matchboxbananasynergy** [comment]
The app itself (APKUpdater) targets Android 14, and indeed, the apps installed via this method have to target above a certain Android version, but that won't really be an issue for most people, who I hope will be using apps that are actively maintained.

The fallback of having a notification to manually update can still be an option, but it would be amazing to have an app *like* Obtainium that implements this API.

**Comment by rumboalla** [comment]
This is already implemented and works well as long as you have installed the app from APKUpdater.
For API 34 there's a way for requesting ownership of an app while doing an update, but I haven't tested this.

**Comment by matchboxbananasynergy** [comment]
> This is already implemented and works well as long as you have installed the app from APKUpdater. For API 34 there's a way for requesting ownership of an app while doing an update, but I haven't tested this.

Glad to hear that it supports the API! I will surely be testing this out.

Perhaps this could be explicitly mentioned in the README (the fact that unattended updates are supported for Android 12+), as a lot of people are looking for that exact feature. :)
