### ISSUE TITLE
[Request] Add currently installed version compared to available update and more

### ISSUE THREAD

**Issue by warmoans** [rumboalla/apkupdater#399]
As the title says id like there to be a way to see the currently installed version compared to the the available update (even tapping the app icon and a pop up showing that info could work). I've attached a screenshot that shows how APKGrabber shows this info. 

I'd also like there to be a way to hide beta updates or any available update I don't want to see like for system apps. For example I don't use the Facebook beta but I use the beta of many other apps. Another related thing is that Google Meet has 3 versions a g version (I believe for Android Go), a s version (for Samsung), and a standard version. They are differentiated with .g or .s added to the standard version name. So a way to hide those updates would be nice as well if able. The attached screenshot shows an example in the available update version. 

Lastly a pull down to refresh available updates would be helpful when using one handed on a big phone. 

I've attached a screenshot that shows 

Let me know if I can clarify.

![Screenshot_20230813-222501](https://github.com/rumboalla/apkupdater/assets/37345461/209ee6b7-2ed6-4d00-96a9-d58c8167d1a4)

**Comment by rumboalla** [comment]
Wrong place for requests.
Already requested.
Already implemented.
