### ISSUE TITLE
App doesn't ignore apps added to ignore list

### ISSUE THREAD

**Issue by craftyguy** [rumboalla/apkupdater#4]
On 1.1.1, adding apps to the ignore list doesn't seem to have any effect, the app still looks for updates

**Comment by rumboalla** [comment]
There was a problem with the default value of the ignore list on first run, it's fixed now. Not sure if it's the same problem though. I will publish a new release soon.

**Comment by rumboalla** [comment]
This should be fixed now.

**Comment by craftyguy** [comment]
Yea this may not be the same problem. It seems like the app is still searching for apps in the ignore list, at least I get "errors" when refreshing. It doesn't actually tell me what the errors are, and ignored apps are still visible on the main screen (though slightly dimmed, is that intentional?)

**Comment by rumboalla** [comment]
That is intentional, ignored apps are displayed with 0.5 alpha. If you are getting updates for apps that are on the ignore then it is a bug, but I haven't been able to reproduce. Could you give me some more information maybe screenshots. I'm planning to add an error log at some point to make troubleshooting easier.

**Comment by craftyguy** [comment]
Ok, I don't see any updates for apps on the ignore list, but I get a
number of errors in a toast message (nothing in logcat) when
refreshing. I had assumed that even though the ignored apps are
dimmed, that they might be the source of the vague errors in the
toast. might I suggest hiding ignored apps completely from the main
window there by default when they are hidden? that would make it
really clean for viewing which apps are not being ignored, and quickly
adding new apps that should be ignored since the ignored ones add a
lot of noise on that window

**Comment by rumboalla** [comment]
If I remove the apps from the list then the user won't have an easy way to add them again.
The vague errors are usually from apps that have a weird version number that's not parsed correctly. Once I add error logging it will be easier to troubleshot this.

**Comment by craftyguy** [comment]
Add a toggle to show ignored apps, but have it off by default?
