### ISSUE TITLE
FLAG_RECEIVER_BOOT_UPGRADE Error

### ISSUE THREAD

**Issue by haniham** [rumboalla/apkupdater#40]
Hello,
I get the following error on the Gigaset QV1030 of my parents. I need it for automatically updating Whatsapp outside of the play store.

![whatsapp image 2017-03-16 at 21 54 40](https://cloud.githubusercontent.com/assets/4102949/24018698/4cb3a234-0a95-11e7-8c03-3152144610c7.jpeg)

**Comment by rumboalla** [comment]
This should be fixed now and will be included in next release.
Thanks for the report!
