### ISSUE TITLE
no fdroid apps populate in search

### ISSUE THREAD

**Issue by ghost** [rumboalla/apkupdater#403]
Only Fdroid store is enabled in settings. I searched for :fennec, simple keyboard, osmand etc. No results. Stuck on loading screen.

all the other stores searches work perfectly (aptoide, apkmirror)

**Comment by rumboalla** [comment]
https://f-droid.org/repo/ is currently returning a 500 error

**Comment by TPS** [comment]
@rumboalla Maybe worth rotating among mirrors found @ https://f-droid.org/en/docs/Running_a_Mirror/ in such cases?

**Comment by rumboalla** [comment]
> @rumboalla Maybe worth rotating among mirrors found @ https://f-droid.org/en/docs/Running_a_Mirror/ in such cases?

Yes good idea. Added to the list https://github.com/rumboalla/apkupdater/discussions/394

**Comment by TPS** [comment]
@rumboalla Better F-Droid mirror list @ https://gitlab.com/fdroid/mirror-monitor/blob/master/README.md#active-mirrors
