### ISSUE TITLE
Update from locally downloaded APK?

### ISSUE THREAD

**Issue by eGit** [rumboalla/apkupdater#405]
Hi,

some apps are installed manually by me. They are not available on major repos like F-Droid, Aptoid, ApkMirror.

My problem is, I cannot update and existing app by installing a newer version of their APK. It always fails. It doesn't allow me to install a newer version of an apk of an app that is already installed. I have to uninstall the app and then the installation of the newer apk works flawlessly.

Could APKUpdater somehow allow updating an installed app with a newer APK somehow?

**Comment by rumboalla** [comment]
Please provide logs and detailed info on what apps are you trying to update and what sources are you using, etc...

**Comment by rumboalla** [comment]
Reopen when you have more info. Thanks
