### ISSUE TITLE
Sliders not usable on Android TV

### ISSUE THREAD

**Issue by rumboalla** [rumboalla/apkupdater#413]
Reported https://github.com/rumboalla/apkupdater/issues/407

**Comment by rumboalla** [comment]
This version has a textfield and dropdown instead of a slider. @peat80 can you test?
[com.apkupdater-debug.zip](https://github.com/rumboalla/apkupdater/files/12398425/com.apkupdater-debug.zip)

**Comment by peat80** [comment]
Tried the debug apk now.
The dropdown works fine with remote control. 
The textfield works too, but you also get stuck using cec remote.
Works fine with native shieldtv remote like on the search field. 👍
