### ISSUE TITLE
Hide columns sliders when android TV UI is enabled 

### ISSUE THREAD

**Issue by maj113** [rumboalla/apkupdater#420]
Since those sliders don't do anything when it's enabled it may be a good idea to hide them especially since people on ATV will probably never actually interact with those anyways

**Comment by rumboalla** [comment]
It is on my todo. Closing since this is not a bug.

**Comment by maj113** [comment]
> It is on my todo. Closing since this is not a bug.

My bad, didn't see the discussion page
