### ISSUE TITLE
Is This Meant To Work With Firestick? Cos It Is Unworkable For Me 

### ISSUE THREAD

**Issue by Nethanswarm** [rumboalla/apkupdater#424]
Hello. Thanks in advance for your time. I installed apkupdater onto my 4k max firestick. It opens and it sees the apps on the device and there is the ui with apps, search, update and settings at the bottom. But when I go into updates and there is an update there to do, when I select the "Install App" button, it opens the link in the Silk browser. And the Silk browser doesn't allow downloads on the firestick. If you try it comes up with "Downloading is not supported at this time". I tried searching for a way to allow it, it doesn't seem possible. I tried changing the default app for web browsing, no option for that in firestick settings, even downloaded a default app manager, still couldn't do that. So unless you add an option in apkupdater to choose what app it uses to open links in (I have downloader on my firestick) regardless of what the firestick has down as the default app for web browsing, the app can tell me which apps need updating, but cannot actually be used to update apps, and so does not work (for me at least) on the firestick. Am I missing something super obvious? Or is it just not meant to work on a firestick? Again, thanks for your time.

**Comment by rumboalla** [comment]
It works great on firesticks. Disable APKMirror source in setttings. The other sources install directly, no need for a browser.

**Comment by Nethanswarm** [comment]
Oh I thought I was missing something obvious. Thanks!
