### ISSUE TITLE
App crash when updating cromite

### ISSUE THREAD

**Issue by samuraikid0** [rumboalla/apkupdater#433]
Tell if you are able to reproduce the crash

**Comment by rumboalla** [comment]
Tested this and I could not reproduce. Do you have logs?

**Comment by samuraikid0** [comment]
Ill get them later night 

Thanks !

**Comment by samuraikid0** [comment]
Ok it crashed because I've upgraded magisk from canary to last stable

Reinstalling apkupdater fixed it
