### ISSUE TITLE
Add translation values-in Indonesian

### ISSUE THREAD

**Issue by HazakuraID** [rumboalla/apkupdater#435]
[Google Drive](https://drive.google.com/drive/folders/1fG1idV_5M7Nlkb5GsGTrOgttJi33A0hh) 
can may please there on this allow drive the download file. thanks you

**Comment by rumboalla** [comment]
Added. Terima kasih!

**Comment by HazakuraID** [comment]
@rumboalla update new translation typo, l forgot yesterday Sorry, there are some in this Language English to replace word current: Indonesia
[Update Translation](https://drive.google.com/drive/folders/1fG1idV_5M7Nlkb5GsGTrOgttJi33A0hh)
