### ISSUE TITLE
Keep getting "you don't have an app to do this"

### ISSUE THREAD

**Issue by kodiadon** [rumboalla/apkupdater#437]
I have the Nvidia Shield 2019 pro. I just installed apkupdater a couple of days ago. When I open it, it searches for updates. It found 2-3 updates, but when I try to update them, I always get the message "you don't have an app that can do this."  
Some of the updates are from Github, some are from Aptoide, or APKmirror, etc.

I do NOT have those apps installed on my shield.  I thought apkupdater would download from those apps and update my apps??

Is it necessary to have those other apps installed on my Shield for apkupdater to work??? Thank you

**Comment by rumboalla** [comment]
APKMirror source needs a browser. The other sources don't need external apps and should install directly. Can you provide logs of what happens when trying to install something?

**Comment by peat80** [comment]
I often install updates from apkmirror on my shield tv.
Works fine if you have a browser installed.
You should try tv bro. It is specifically made to work with just tv remotes. 😀

**Comment by kodiadon** [comment]
If you tell me how to provide logs, I'll do that. Thank you.

**Comment by rumboalla** [comment]
> If you tell me how to provide logs, I'll do that. Thank you.

```adb logcat```

**Comment by rumboalla** [comment]
You can reopen with logs
