### ISSUE TITLE
bug(search): searching for package name or app name doesn't work correctly

### ISSUE THREAD

**Issue by AnonymousWP** [rumboalla/apkupdater#445]
1. Type the app name or package name in the search field
2. Notice how it doesn't return the correct app or no app at all

I can include a logcat later if needed.

**Comment by rumboalla** [comment]
What source?

**Comment by AnonymousWP** [comment]
> What source?

GitHub and APKMirror.

**Comment by rumboalla** [comment]
Works here
![Screenshot_20230911_212353](https://github.com/rumboalla/apkupdater/assets/21153554/425bcacb-b635-4f39-9e87-af96ca8b64bd)

**Comment by AnonymousWP** [comment]
> Works here
> ![Screenshot_20230911_212353](https://github.com/rumboalla/apkupdater/assets/21153554/425bcacb-b635-4f39-9e87-af96ca8b64bd)
> 

Now try typing "APKUpdater" without "com". I think it's that. In some cases, app names or package names are very long.

**Comment by samuraikid0** [comment]
I was also woundering about this

 can't the search be fetch by name instead app name ? adding another string name

**Comment by rumboalla** [comment]
> 
> Now try typing "APKUpdater" without "com". I think it's that. In some cases, app names or package names are very long.

I get the same results.

**Comment by samuraikid0** [comment]
Yes, it's working
 I've had search for yet to build app

**Comment by AnonymousWP** [comment]
Hmm, very weird, today it's working as intended.
