### ISSUE TITLE
feat(ignore-app): hold to ignore app in update tab

### ISSUE THREAD

**Issue by AnonymousWP** [rumboalla/apkupdater#446]
Right now, you need to go to the 'Applications' tab and scroll a lot to then ignore the app, which is obviously a lot of work.

**Comment by AnonymousWP** [comment]
Alternative would be to include this in the search tab (as well). It's way too much effort now to exclude an app.

**Comment by rumboalla** [comment]
Please use Discussions for feature requests

**Comment by AnonymousWP** [comment]
> Please use Discussions for feature requests

But look what I said here: https://github.com/rumboalla/apkupdater/discussions/393#discussioncomment-6865491. I don't like using Discussions for that, but I guess I have no choice.
