### ISSUE TITLE
bug(apkmirror): refreshing sometimes returns different results

### ISSUE THREAD

**Issue by AnonymousWP** [rumboalla/apkupdater#448]
As you can see in the screen record, the first time it searches for updates, the results are different than from the second refresh (which was right after it as you can see). The first refresh returned more results.

I use APKMirror and GitHub as source. Let me know if you'd like a Logcat (although it's pretty hard to filter out personal information).

https://github.com/rumboalla/apkupdater/assets/50231698/86327a50-3c3c-431a-bb91-9e2067023d7d

**Comment by rumboalla** [comment]
Both GitHub and APKMirror will rate limit if you make too many requests. This is probably what happened, but it's hard to say without logs.

**Comment by AnonymousWP** [comment]
Good point, but even after many hours, I check again and the first time returns less results than the day before (auto-updating on the Play Store is disabled). Here's a Logcat (I seem to have found it, so I removed all useless information).
[logs.txt](https://github.com/rumboalla/apkupdater/files/12596472/logs.txt)

And yes, it could be their API, but I think I have this issue since a particular version of APKUpdater. I'd be surprised if their API would have issues for many days/weeks.

**Comment by rumboalla** [comment]
Closing this since I still don't see any evidence of this happening apart from the timeouts.

**Comment by AnonymousWP** [comment]
> Closing this since I still don't see any evidence of this happening apart from the timeouts.

You can't reproduce it either? I can deliver more screenshots too if required. Also, then why didn't it happen with v2?

**Comment by AnonymousWP** [comment]
This issue is still always occurring, even if I use it after I woke up (which means it can't be caused by a ratelimit). Also, if it's still happening so many times, then it's clearly not an APKMirror issue. Every single refresh displays different results.

I feel like this issue should be re-opened, as it's still an issue I can easily reproduce. The fact that you don't see evidence doesn't mean it's not an issue.

**Comment by AnonymousWP** [comment]
In fact, I just downloaded 2.0.5 (https://github.com/rumboalla/apkupdater/releases/tag/2.0.5) again and it's much better and I don't have any issues. It even displays many more apps that actually do have an update available with even less false positives too. Especially many Google apps have an update available on 2.0.5, and that's without me talking about WearOS version.

**Comment by rumboalla** [comment]
> In fact, I just downloaded 2.0.5 (https://github.com/rumboalla/apkupdater/releases/tag/2.0.5) again and it's much better and I don't have any issues. It even displays many more apps that actually do have an update available with even less false positives too. Especially many Google apps have an update available on 2.0.5, and that's without me talking about WearOS version.

Please provide concrete example so I can investigate this.

**Comment by AnonymousWP** [comment]
> > In fact, I just downloaded 2.0.5 (https://github.com/rumboalla/apkupdater/releases/tag/2.0.5) again and it's much better and I don't have any issues. It even displays many more apps that actually do have an update available with even less false positives too. Especially many Google apps have an update available on 2.0.5, and that's without me talking about WearOS version.
> 
> Please provide concrete example so I can investigate this.

Sure, thank you. Here's a screen record. I think it has to do with the fact that 2.0.5 reports a time-out while 3.0.1 doesn't and only provides half of the packages while 2.0.5 will just not return any results, which makes more sense. But then we still have the problem that 2.0.5 does fetch updates for Google apps while 3.0.1 doesn't, showcasing that here:

https://nx32835.your-storageshare.de/s/tYw95FmLDXqzygm (can't upload it due to the file size limit. Double-click to open full-screen, otherwise you won't be able to see the full phone screen)

Now I check the apps side-by-side: looks like it's caused by the option "Ignore system apps" that's absent at 3.0.1. Google apps are system apps, so yeah. Also, in this live demo you can see how it requires me three times to fetch updates (the first two result in an empty list).
