### ISSUE TITLE
Ignore updates/apps from Updates tab

### ISSUE THREAD

**Issue by DeicPro** [rumboalla/apkupdater#45]
As the title says, a way to can ignore apps from Updates tab to no need to ignore all system apps that not want manually (is bored, so many apps to ignore...) and can ignore just that update or all future updates (current ignore) choosing the desired option.

**Comment by Mrgts411** [comment]
yeah, this feature would be awesome.

**Comment by rumboalla** [comment]
This is now implemented and will be included next release.

**Comment by tjsuominen** [comment]
Not doable in latest.
