### ISSUE TITLE
Enhancement requests/ideas 

### ISSUE THREAD

**Issue by Helpful-Neko** [rumboalla/apkupdater#453]
I've just started using your app it's awesome! I love how it's able to check for updates over so many different sources. Thank you so much for the effort you've put into this project 😸

I have a few ideas that I think could greatly improve the experience or might just be useful. 

(1) Ability to see updates source and applications source. For example tapping on the application to see it's source or the source for a update. 

Example say you're updating a application [Example APKUpdater] somehow being able to bring you to the source of the new update [Example https://github.com/rumboalla/apkupdater/releases/tag/3.0.1 or F-Droid, APK mirror, ect] or when viewing apps in the apps section. Being able to tap on a application [Example APKUpdater] and have it redirect you to its web/source page [GitHub, F-Droid, app info, ect]

Theses features would make it a little bit more convenient to see whats in the new update (instead of blindly updating it) and saves time in my opinion. 

(2) The ability to ignore updates for certain applicants alongside ignoring the current update (But being able to install them at a later time) similar to what Droid-Ify offers but for the update 👍 screen and app section. 

(3) Being able to have Shizuku Installer as a 3rd installer option instead of only offering root install options. I could see that benefiting none root users. 

(4) I'm not sure if this is already a option (That I haven't found) but having the ability to have some applications set up to automatically update but having it set up where others can be manually updated. That would help with applications that are sometimes know to be released with bugs/issues in their newer versions.

Thank you for your time and I hope maybe some of these ideas might be useful 😸

**Comment by rumboalla** [comment]
Please use the correct thread to request features. Also some of these features are already on the list.
https://github.com/rumboalla/apkupdater/discussions/393
