### ISSUE TITLE
App updates changelog

### ISSUE THREAD

**Issue by matt873** [rumboalla/apkupdater#454]
Can you add changelog/what's new to the app updates menu? If that is too much work then please add an option to open the releases page for the current release for F-droid and Github apps.

**Comment by rumboalla** [comment]
There's already a changelog for sources that support it.

**Comment by matt873** [comment]
> There's already a changelog for sources that support it.

So for GitHub and F-droid, can you add the releases page URL? It would be easier because manually typing every app name in the browser and going to GitHub and F-droid releases page is very time-consuming, especially when viewing multiple app updates changelogs.

**Comment by rumboalla** [comment]
Added this to the list https://github.com/rumboalla/apkupdater/discussions/393

**Comment by matt873** [comment]
As a suggestion, you can also add the official GitHub page link to the GitHub icon on the search results page which would enable us to verify that the app to be downloaded is from an official page and is not some forked or modified one.
![Screenshot_20230918-202141_1](https://github.com/rumboalla/apkupdater/assets/108935493/29d4dde2-53f9-4980-a378-c74c60874494)
