### ISSUE TITLE
Crash during hiding apps

### ISSUE THREAD

**Issue by Alezzzander** [rumboalla/apkupdater#455]
Hello!
Possibly related to https://github.com/rumboalla/apkupdater/issues/412
Found one bug/crash:
1. When i want to hide app to stop tracking it ,apkupdater crashes with notification or just stop working without notification,but it happens not with each app i want to hide. E.g. I have 10 apps to hide and crash can appeared 2 times during hiding all these 10 apps. 
No specific app triggers this error.Happens randomly.
My phone: Huawei y91

**Comment by rumboalla** [comment]
Do you have logs for this?

**Comment by rumboalla** [comment]
Duplicate of https://github.com/rumboalla/apkupdater/issues/412
