### ISSUE TITLE
Separate sections to stable and beta apps

### ISSUE THREAD

**Issue by DeicPro** [rumboalla/apkupdater#46]
As the title says, can have got a separate sections to can see stable and beta apps together or shows in the app card as:
—
AppName
PackageName
VersionName

Stable: VersionName [APKMIRROR] [EVOZI]
Beta: VersionName [APKMIRROR] [EVOZI]
—

If can to be configured if separate section or in the app card, better.

**Comment by rumboalla** [comment]
Betas are now marked with an icon and betas are sorted down.
