### ISSUE TITLE
[Request] Compile-time option to disable the search tab

### ISSUE THREAD

**Issue by mpc-v** [rumboalla/apkupdater#460]
I'm trying to make my phone as distraction-free as possible while still keeping my needed apps up to date. The search feature makes it too easy to install distracting apps in moments of weakness. A compile-time option to disable search would greatly reduce my ability to install distracting apps. I am not asking you to provide builds with this option (though that would be really great).

**Comment by rumboalla** [comment]
Please use the new features thread https://github.com/rumboalla/apkupdater/discussions/393
