### ISSUE TITLE
Randomize daily update time

### ISSUE THREAD

**Issue by archon810** [rumboalla/apkupdater#470]
Hi @rumboalla,

As you may know, I run APKMirror, and I wanted to reach out with an API issue I've noticed.

You see, every hour on the hour, there are large spikes in requests to the APKMirror API endpoint responsible for checking if an app is already on the site or not. The worst spike seems to be at 9AM Pacific, I'm not sure why exactly, but it could be maybe where it's the default daily check time for the largest chunk of APKUpdater users.

Have a look:
![image](https://github.com/rumboalla/apkupdater/assets/469543/fae809f8-6dd9-47e1-a39d-1d27f8a2db5c)

If possible, can you think of a way to spread out the check times more uniformly? Even starting on a random minute would help distribute it 60 more ways.

Thanks.

**Comment by rumboalla** [comment]
I have added a -15 to +15 min random delay that should even the spikes.
2b0eeef3916f6b986a822d49e7c95a1d5a0fb5bc

**Comment by archon810** [comment]
Thank you, may I ask why not +/- 30 to make it really even?

**Comment by rumboalla** [comment]
> Thank you, may I ask why not +/- 30 to make it really even?

30 mins difference with the time selected by the user doesn't sound good, but if this doesn't help we can change it again.

**Comment by archon810** [comment]
Well, I think 15 minutes is just as arbitrary, and users who expect to receive update checks exactly on the hour would still be confused.

I think the right way to do this is to be upfront about the fuzziness and provide a little explainer for the reason in the settings.

By the way, do you know when live users are going to start receiving the initial update with the tweaks?

**Comment by rumboalla** [comment]
> Well, I think 15 minutes is just as arbitrary, and users who expect to receive update checks exactly on the hour would still be confused.
> 
> I think the right way to do this is to be upfront about the fuzziness and provide a little explainer for the reason in the settings.
> 
> By the way, do you know when live users are going to start receiving the initial update with the tweaks?

With next release, which should be soonish.

**Comment by rumboalla** [comment]
I've changed it to 0-59 mins, and this is released now.
