### ISSUE TITLE
Don't show number of apps

### ISSUE THREAD

**Issue by je-vv** [rumboalla/apkupdater#474]
There are 4 tabs shown at the bottom, apps, search, updates and settings.  It's cool that when updates are found for not ignored apps, then the updates tab shows the amount of updates found and available.

However, for no special reason, the apps tab keeps always showing the total amount of apps detected by apkupdater, and it does so on a accented color (sort of magenta, on my system dark theme).  I don't see a need for the apps tab to call my attention.  I do see the need on the updates tab, but not on the apps one.

**Comment by rumboalla** [comment]
You can use the feedback thread for this https://github.com/rumboalla/apkupdater/discussions/396
