### ISSUE TITLE
f-droid re-inclusion

### ISSUE THREAD

**Issue by je-vv** [rumboalla/apkupdater#475]
Can apkupdater be included on f-droid?  Some time back it was found on f-droid.  Since the app ceased maintenance for some time, it was dropped.  Now that it's back, can it also be included on f-droid?  If too much hassle, perhaps offer a custom f-droid repo for apkupdater?

Thanks !

**Comment by rumboalla** [comment]
You can find it on IzzyOnDroid repo

**Comment by je-vv** [comment]
I see, thanks !  Though I didn't want to use IzzyOnDroid, it has shared apps with official f-droid, and I know no way to select which repo to prefer when the same app is kept on more than one repo (my current understanding is that what comes newer is grabbed and apps get updated to latest, and that is OK for apps which really need to be up to date such as newpipe, however in general I'd like to prefer official repo and not unofficial ones).
