### ISSUE TITLE
updated, Translation to activity offline it busy still happens if when rarely.

### ISSUE THREAD

**Issue by HazakuraID** [rumboalla/apkupdater#476]
![Screenshot_2023_1105_164059](https://github.com/rumboalla/apkupdater/assets/105591857/afdc2b02-0a6f-4aee-ad1f-151415c8316d)
(Offline red and Green Online)
different online for color less frequent in Get the Telegram group or Discord directly, need you for help  "issues" and "pull requests" daily activities.

**Comment by AnonymousWP** [comment]
Why did you close this?

**Comment by HazakuraID** [comment]
> Why did you close this?

This is what I mean, because for some reason the online hasn't happened yet activate or activity language is helpful or maybe there is a translation. And [check](https://github.com/rumboalla/apkupdater#translations) Contribution activity due to changed commit to disappear After about not often 2-3 months ago, 

*Sorry to this not believe you "all closed" be so sad.
