### ISSUE TITLE
VT Reports

### ISSUE THREAD

**Issue by IzzySoft** [rumboalla/apkupdater#479]
Any idea what's going on here? Reports at VT for the last 3 versions don't look good:

* [v3.0.0](https://www.virustotal.com/gui/file/0bc3293ba5e12d3b8c273634019b957538f07c31397244b1947baaed1d0edfe8/detection/f-0bc3293ba5e12d3b8c273634019b957538f07c31397244b1947baaed1d0edfe8-1693280722) 8 (false?) positives
* [v3.0.1](https://www.virustotal.com/gui/file/d4ed7218ff758cc93e7f5fdf261910a5c950b30fa78df0c09a8da130617d280e/detection/f-d4ed7218ff758cc93e7f5fdf261910a5c950b30fa78df0c09a8da130617d280e-1694619943) 8 (false?) positives
* [v3.0.2](https://www.virustotal.com/gui/file/f2fa12831f5eb9b07859e9c21c7abffad92a16f756ad2e86eb5cc63f13d05b01/detection/f-f2fa12831f5eb9b07859e9c21c7abffad92a16f756ad2e86eb5cc63f13d05b01-1699195339) 4 (false?) positives

I've removed the 2 older versions [from my repo](https://apt.izzysoft.de/fdroid/index/apk/com.apkupdater) now. The latest one with "only" 4 I'll leave there for 24h waiting for your response – but only as the reported "offender" is known to have caused "false positives" for quite some time now (search the web for "Android:Evo-gen" to find a load of those and find e.g. [GSMArena](https://www.gsmarena.com/no_our_android_app_doesnt_contain_a_virus-news-52893.php) from 2022, [Avast Mobile Evo-gen Trojan bug is back again?](https://community.appinventor.mit.edu/t/avast-mobile-evo-gen-trojan-bug-is-back-again/40273) from 2021, and many more. Thing is, while Avast has a history of false positives especially with this one, Avira, Cynet and F-Secure also report it, so please check.

For Avira, there're [similar things](https://community.iode.tech/t/malware-in-release-4-3-2-of-aurora-store/1934) with e.g. Aurora Store. I found no hits for the other two engines, but assume these are "bad signatures" with all of them. Nevertheless, it cannot hurt to check. Please do, as these reports were already reaching me asking to remove your app from my repo. A timely response is much appreciated. Thanks!

**Comment by TPS** [comment]
What's peculiar to _me_ is that, though VT is a sibling company & presumably is used in the service, GPlay Protect has _never_ flagged APKUpdater on my stock unrooted Android, even those last 3 versions, so it seems Google itself doesn't believe those reports?!

**Comment by IzzySoft** [comment]
Probably they came to the very same conclusion ("false positives"). Btw, AFAIK VT is run by Google even, isn't it?

That said, I'd be interested if there was anything "suspicious" found e.g. during the build process (like what libraries/modules are downloaded then and may have triggered this).

**Comment by rumboalla** [comment]
Duplicate please use one thread for this https://github.com/rumboalla/apkupdater/issues/479

**Comment by IzzySoft** [comment]
@rumboalla this is a duplicate of itself? :thinking: If I follow your link, I'll end up here again.

**Comment by IzzySoft** [comment]
Ah, there: #465 – OK, thanks. Must have missed that, apologies.
