### ISSUE TITLE
Wrong Play Services DPI suggested by app

### ISSUE THREAD

**Issue by warmoans** [rumboalla/apkupdater#483]
The app showed an update for Google Play services and linked to the download page the 480dpi version on my Pixel 7 Pro, when the Play Store pushes me the nodpi version. 

Also I already have the newest play services installed with reg correct dpi but the app is still showing the 480dpi version as an available update.

**Comment by rumboalla** [comment]
Please provide more information like the version name and version code of the installed app and updates.

**Comment by warmoans** [comment]
This was the version that the app suggested I download https://www.apkmirror.com/apk/google-inc/google-play-services/google-play-services-23-44-14-release/google-play-services-23-44-14-190408-580326705-android-apk-download/

And this is the version that the play store had already installed. 

https://www.apkmirror.com/apk/google-inc/google-play-services/google-play-services-23-44-14-release/google-play-services-23-44-14-190400-580326705-2-android-apk-download/

**Comment by rumboalla** [comment]
Not much I can do about this, the version names don't match and the version code is higher so it counts as an update.

**Comment by TotallyAvailable** [comment]
Same issue with a lot (and I mean a LOT) of other Apps.
Take Chrome, Webview + -Library Dev with the usual (several hour) delay between the availability of the ...031 and ...033 builds (BIG difference, do NOT mix).

Not starting again with relation to https://github.com/ImranR98/Obtainium/issues/946 , there could still be the case made to allow for manual blacklisting, given that you went with implementing the option to ignore a given update.
How about a 'reason for ignorance' or just a simple (x) button linked to 'never suggest string ending in [31] again' (As there is consistency here).

Again this would cover very few apps for a given rule (frequent user of the app might've spotted the patterns for their set of Apps), in fact there should be no rules, purely per app, requires a lot of background work and even more user knowledge on what they are about to do and the consequences of doing so.

And the more I type here, suggesting solutions, the more I get lost myself, in the complete desaster that is version numbering on top of the limits imposed by APKM.

Long story below a 'wontfix' coming to a similar conclusion. Probably the way to go until something big changes...like crowd sourcing the required information already done with the manual inclusion of GitHub repos as update sources ?...
