### ISSUE TITLE
Translation to Korean

### ISSUE THREAD

**Issue by Apious** [rumboalla/apkupdater#486]
[strings-ApkUpdater.zip](https://github.com/rumboalla/apkupdater/files/13555577/strings-ApkUpdater.zip)

i'd like to change the name
[ <string name="settings_android_tv_ui">안드로이드 TV UI</string> ] to 
기본 썸네일(Default thumbnail) > 타일 형식(tile format)

as this
<string name="settings_android_tv_ui">타일 Ui(Default)</string> or <string name="settings_android_tv_ui">가로형(horizontal) Ui</string>

thx :)

**Comment by AnonymousWP** [comment]
Why didn't you make a pull request instead?
