### ISSUE TITLE
Add support for apkcombo

### ISSUE THREAD

**Issue by Jvr2022** [rumboalla/apkupdater#488]

**Comment by TotallyAvailable** [comment]
> Ordered by importance.
> 
>* Play store (with bundle support)
>* ~Gitlab~, Hosted GitLabs.
>* Codeberg
>* Custom F-Droid repos. Support F-Droid mirrors.
>* ~ApkPure~
>* Uptodown
>* RSS sources
>* Source with support for custom list of urls.
>* Apkcombo
>* Apkflash
>* Galaxy Store

https://github.com/rumboalla/apkupdater/discussions/394#discussion-5515511

**Comment by franco27** [comment]
I would also like the source Uptodown.
