### ISSUE TITLE
Accuracy of APKUpdater

### ISSUE THREAD

**Issue by SkewelVsAll** [rumboalla/apkupdater#491]
Hey,

I was wondering - how do I know that the webpage that APKUpdater opens for an updatable app is the right one for my device? 

In my case, I'm facing a bug with Google Play Store on my Galaxy S23 Ultra where random apps keep updating for no reason and disappear as soon as I cancel them even the progress wheel beside the applications keeps spinning and does nothing, they seem like ghost updates basically.

So, I thought I'll reset the store and uninstall the latest Google Play update that's been installed on my phone through settings and update it manually.

Supported sources like APKmirror seems to have multiple variants of a single version of Play Store if I check manually, so how do I know the version that APKmirror shows me via APKUpdater is the right one for my phone?

**Comment by rumboalla** [comment]
APKUpdater will try to select the correct apk for your device with the available information. The accuracy of it will depend on the source. If there are specific cases where you are not getting the correct apk you can report them here.
