### ISSUE TITLE
Bump the versioncode

### ISSUE THREAD

**Issue by krt16s** [rumboalla/apkupdater#5]
You are happily upping the versionname, but as far as Android is concerned, this is not a new version. Android checks the versioncode integer, if its higher, its an update, if not, its just another flavor of the same version and cannot be upgraded. Upping the version code in `./app/build.gradle` should fix that.

Please see https://developer.android.com/studio/publish/versioning.html for more information.

**Comment by rumboalla** [comment]
You are right, I will be updating it with every new version. Thanks!
