### ISSUE TITLE
Enhancement: Update All button

### ISSUE THREAD

**Issue by imxade** [rumboalla/apkupdater#500]

**Comment by AnonymousWP** [comment]
To explain you why your issue was closed: Rumboalla somehow prefers you to file feature requests at https://github.com/rumboalla/apkupdater/discussions/393.

**Comment by maj113** [comment]
This (to me) looks like a pretty bad idea, most updates come from APKmirror which APKUpdater can't even update from directly, there are also sources that can be potentially unsafe/dangerous, you also risk breaking any system app that gets updated in the process
