### ISSUE TITLE
feature request: add an icon to updates that takes you to the website source of that update

### ISSUE THREAD

**Issue by rezad1393** [rumboalla/apkupdater#501]
feature request: add an icon to updates that takes you to the website source of that update.

so for example if an app has an update on f-droid, on that app add a link for that app update page on fdroid

same with apkpure and so on.

**Comment by rezad1393** [comment]
is this completed?

**Comment by Bakr-Ali** [comment]
@rumboalla I came here by searching to see if anyone requested this feature before requesting it. 

It was closed as completed but it doesn't seem to be the case? When I click on the icon of the source website it doesn't do anything.
