### ISSUE TITLE
Provide file size in app updates list

### ISSUE THREAD

**Issue by gracie95** [rumboalla/apkupdater#503]
I think it's not enough if you obtain all updates updates without showing the apps size. 
Without this, I don't know exactly how bigger or smaller the updates are. 
File size sometimes becomes an important thing.
This may be not limited to Updates. You can also add it to Apps list.

**Comment by AnonymousWP** [comment]
Why has this been closed as 'completed' if the feature isn't on the feature list nor did you implement it?
