### ISSUE TITLE
apkupdater stucks after checking for updates

### ISSUE THREAD

**Issue by du33169** [rumboalla/apkupdater#505]
My phone lost response to any action after checking for updates in "update" tab. I cannot close apkupdater or lock my screen, the only thing I can do is a force reboot. 
This happens especially when there are more than 20 updates. 
Is it possible to use recycleView for better performance?

**Comment by rumboalla** [comment]
Please provide logs and more information about your phone.

**Comment by rumboalla** [comment]
Feel free to reopen with additional info
