### ISSUE TITLE
Version 3.0.3 Android Marking as Unsafe

### ISSUE THREAD

**Issue by PeterKW** [rumboalla/apkupdater#512]
https://apt.izzysoft.de/fdroid/repo/com.apkupdater_52.apk

Any idea why the install is being blocked?

**Comment by rumboalla** [comment]
File looks good. What exactly is the problem?

**Comment by PeterKW** [comment]
https://apt.izzysoft.de/fdroid/repo/com.apkupdater_52.apk

![Screenshot_20240220-215812.png](https://github.com/rumboalla/apkupdater/assets/13779157/ea7ebf75-501c-4977-b6b6-c0ba00a5d960)

**Comment by PeterKW** [comment]
Not sure how to get more details from Google on why it's being blocked? I'm sure it's firing a warning to harshly but I'm wary of dismissing messages like that in general

**Comment by rumboalla** [comment]
Looks like the standard bullshit message from play protect. The app collects zero data.

**Comment by yushiyangk** [comment]
Can confirm it does this on my phone as well, Android 15.

I checked that 3.0.0 also triggers this warning, but the old 2.0.5 does not.

**Comment by Korb** [comment]
> https://apt.izzysoft.de/fdroid/repo/com.apkupdater_52.apk

I got the same notification when trying to install APKUpdater v3.0.3 (**2024-01-30**) from the IzzyOnDroid directory:

> Google Play Protect
> Unsafe app blocked
> This app can collect data that could be used to track you.
> Installing this app may put your device at risk.
> Learn more about Play Protect.

---
Model: Vivo T1 (4G) / V2153
OS version: Funtouch OS 14
Hardware version: MP_0.1
Build number: PD22010F_EX_A_14.2.14.0.W20
Baseband version: .HA.1.1.c2-00054-DIVAR_GENSP_PACK-1.29062.10 7
Kernel version: 4.19.157-perf+. 1 Thu May 8 10:36:27 CST 2025
Compile time: 8 May 2025 05:31:38
Android security update: **1 May 2025**
Google Play system update: 1 April 2025
Software parameter update: 14 March 2025
