### ISSUE TITLE
APKupdater is not showing all update results

### ISSUE THREAD

**Issue by asds86** [rumboalla/apkupdater#52]
APKupdater is not showing all update results, when I refresh the updates tab It will show the majority of apps that have updated versions available but manually going to the site's I'd see that there is a version available on and APKupdater has simply not received the alert that there is an updated version.

Thanks.

**Comment by rumboalla** [comment]
Please provide examples.

**Comment by asds86** [comment]
Example: On 11th may apkpure had an update for the game (squad strike 3) knowing that this update was available on there website, I ran APKupdater to see if there where any updates available and it came back with no available updates I double checked and the update was on the site, I have also tried reinstalled your app.

Although I am not Shure where the problem lie's be that server side as in the search results are coming back as false negative or the app (version) itself is buggy in that it has found the update but has failed to show ALL updates due to loading issues.

**Comment by asds86** [comment]
Also if I was to rotate the screen mid search the updates shown would disappear off screen, meanwhile the app continues to refresh and show further apps.

Thanks.

**Comment by rumboalla** [comment]
I tried with squad strike 3 and could not reproduce this.
Also the second thing you mention is not a problem. Even if you rotate when the search finishes all the updates are added to the list.
