### ISSUE TITLE
Pixel 7 Pro is freezing

### ISSUE THREAD

**Issue by guberm** [rumboalla/apkupdater#522]
The device is freezing and sometimes the app crashes after the app finished installation

**Comment by rumboalla** [comment]
Please provide logs.

**Comment by guberm** [comment]
How can I fetch the logs?

**Comment by rumboalla** [comment]
```adb logcat```

**Comment by Ahoura-Bagherfar** [comment]
I found the solution. When I enter the app, I go to the settings page. When the list of updates is loaded, I go to the update page

**Comment by rumboalla** [comment]
Please reopen with logs
