### ISSUE TITLE
APKUpdater quiet installation

### ISSUE THREAD

**Issue by FelixFester** [rumboalla/apkupdater#533]
Just noticed that if I'll install APKUpdater as system app, there would be possible to silently update already installed apps. But installing new apps would work only with default Android pop-up window appearing.
![Screenshot_20240329-230540_Установщик пакетов_1](https://github.com/rumboalla/apkupdater/assets/59778334/533ab739-9c62-4181-a2f8-a2f557ca04f5)

So I think it would be nice if you'll add quiet installation in this case everywhere + hide "Root installation method" if the app has been installed as system app (Root installation method doesn't work anyway in latest version, according to other reported issues and from what I'm seeing).

**Comment by rumboalla** [comment]
Silent install is supported on Android 12+ and you don't need to be a system app.
