### ISSUE TITLE
Installation and searching

### ISSUE THREAD

**Issue by FelixFester** [rumboalla/apkupdater#534]
Some apps from ApkMirror is not searchable 
![Screenshot_20240330-000840_APKUpdater](https://github.com/rumboalla/apkupdater/assets/59778334/7eac0c88-2654-43b3-b34c-e34f0243da97)
![Screenshot_20240330-000805_Mull](https://github.com/rumboalla/apkupdater/assets/59778334/76e30a2f-21b2-4717-bc2e-ec7418572124)

And in the case of .xapk files from APKPure, APKUpdater can't do anything with them so there's a installation error. But it's possible to download .xapk anyway. + Search for some reason sometimes can show results only from one source and then after installation (for example from Aptoide) show what there's update from ApkPure.

**Comment by rumboalla** [comment]
ApkMirror search is a hack and there's no plans to improve it unless there's api support.
XAPK are supported, if it doesn't work make a proper bug report.
