### ISSUE TITLE
Play Source: App names and changelog shown in different language

### ISSUE THREAD

**Issue by burakdede0** [rumboalla/apkupdater#535]
App names and changelog are shown in French for me since the beginning of the Play Source addition. My system language is English (US) and it's the only language enabled. Other sources are in English.

Current version: 525-ci
Android 14

![Screenshot_20240403-192636.png](https://github.com/rumboalla/apkupdater/assets/29973158/ef8afdb7-2f9e-49c4-ae5d-351120afb99f)

**Comment by rumboalla** [comment]
This depends on the account used and it's outside my control.

**Comment by franco27** [comment]
Hello
I have a French Google account, yet I wrote to them in English even though my phone has French as the default language and my Google account is in French.

Moreover, I also installed Aurora Store to receive updates from the Google Play Store. And the logs of updated applications are in French.

**Comment by franco27** [comment]
![IMG_20240413_043951.jpg](https://github.com/rumboalla/apkupdater/assets/31793920/882d8287-095d-4a7f-a09f-0571decb46d3)

![IMG_20240413_043903.jpg](https://github.com/rumboalla/apkupdater/assets/31793920/c0c6b933-beb8-446c-9ebd-9179946fb569)
