### ISSUE TITLE
Suggestion: after installation, delete the APK file

### ISSUE THREAD

**Issue by franco27** [rumboalla/apkupdater#537]
Hello
I have noticed that after installing several updates, the size or space occupied by your application increases or doubles, triples, ...

It would be useful to add a setting to clean the application cache on closure, or to delete the installation file after installation.

**Comment by rumboalla** [comment]
In most cases the apk is not even stored on disk, and in the cases where they are they get deleted after use.
What grows in size is the network cache. I added this in here https://github.com/rumboalla/apkupdater/discussions/393
