### ISSUE TITLE
Missing versions on the updates tab

### ISSUE THREAD

**Issue by electriquo** [rumboalla/apkupdater#538]
I am using APKUpdater for years. During the years it got a GUI face lift. Since then, I cannot see the current and the new\updated version in the updates tab in the same as the image in the documentation shows

![](https://private-user-images.githubusercontent.com/21153554/263812047-c4679c1b-09d4-429d-9160-77d4d33b0a0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NjkxNDgsIm5iZiI6MTcxMjQ2ODg0OCwicGF0aCI6Ii8yMTE1MzU1NC8yNjM4MTIwNDctYzQ2NzljMWItMDlkNC00MjlkLTkxNjAtNzdkNGQzM2IwYTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA1NDcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ZmE5YTVhZDM3YzM5Zjg0NDEwMTgxNTg3NzliNTBhMTAzYjI2Y2EwMmNhNTdlYTMzMDUyNDY3ZDQ4MWRjYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tMx313HenaoFrirEZGBd6kTnqZ1SYXaOkm-aDCANLOk)

In the settings, I couldn't find how to make it show.
Is this a bug? Otherwise, would appreciate a guidance on how to get such view.

**Comment by rumboalla** [comment]
The TV UI switch.

**Comment by electriquo** [comment]
Maybe worth to update the documentation or add a caption near the screenshots.
