### ISSUE TITLE
Apps with dashes in version number don't check properly

### ISSUE THREAD

**Issue by thurask** [rumboalla/apkupdater#54]
Take the Samsung Clock app (or most Samsung apps anyway) as an example: I have version 7.0.70-45 on my phone while there's 7.0.70-46 [on APKMirror](http://www.apkmirror.com/apk/samsung-electronics-co-ltd/samsung-clock/). In APKupdater the clock app doesn't appear as having an update available when I check for updates, even though it recognizes that it's version 7.0.70-45. The same goes for the Bixby apps.

**Comment by rumboalla** [comment]
This is fixed in dev branch and will be included in next release. Cheers!
