### ISSUE TITLE
Improve download logic

### ISSUE THREAD

**Issue by d4f5409d** [rumboalla/apkupdater#545]
Currently when there are network issues, there are no options to pause or quit downloading updates or indicate what % of it is downloaded of the selected app.

**Comment by rumboalla** [comment]
Use https://github.com/rumboalla/apkupdater/discussions for feature requests

**Comment by d4f5409d** [comment]
What the?
Well, okay, it's weird

**Comment by AnonymousWP** [comment]
Yeah well, who would have thought issues were going to be used for feature requests, like literally everywhere else. 🙃

**Comment by d4f5409d** [comment]
Haha, nice joke
