### ISSUE TITLE
For this application, I also encountered the same issue. See screenshot.

### ISSUE THREAD

**Issue by MehmOzil** [rumboalla/apkupdater#551]
For this application, I also encountered the same issue. See screenshot.
This application was in French language (French version), but after updating with your application, it became in English version.
Like the internet browser, in the settings, you cannot choose the language.

![IMG_20240509_040506.jpg](https://github.com/rumboalla/apkupdater/assets/31793920/cb60330a-3dc9-437c-bb45-7135b64f5966)

An example for log  of a version number

![IMG_20240413_043951.jpg](https://github.com/rumboalla/apkupdater/assets/31793920/125c2ae1-7a12-4ee8-ae68-6418f9345106)

![IMG_20240413_043903.jpg](https://github.com/rumboalla/apkupdater/assets/31793920/1982ef5e-cd5a-47d9-869c-173576587164)

_Originally posted by @franco27 in https://github.com/rumboalla/apkupdater/issues/547#issuecomment-2102734648_

**Comment by rumboalla** [comment]
Duplicate
