### ISSUE TITLE
Cannot directly install from Google Play on BlackBerry Android

### ISSUE THREAD

**Issue by thurask** [rumboalla/apkupdater#57]
BlackBerry DTEK60 (Marshmallow 6.0.1) cannot directly install APKs using the Google Play API and app version 1.5.0. The APK downloads, APKupdater minimizes but nothing is installed. Logcat of attempting to update Android Pay and failing is linked below.

https://paste.ee/p/yxWVz

**Comment by rumboalla** [comment]
Next release will include a fix that may have fixed this.

**Comment by rumboalla** [comment]
Is this fixed now?

**Comment by thurask** [comment]
No, not yet.

https://paste.ee/p/YB9Xx

**Comment by rumboalla** [comment]
I've made another small change and the crash should be fixed now, but I still don't know why the app is not installing.
If you click on the download completed notification, or try to run the downloaded file manually, does it install?

**Comment by thurask** [comment]
If I tap on the notification it disappears and "Can't open file" pops up.

Which folder is the apk file stored to?

**Comment by rumboalla** [comment]
/data/data/com.android.providers.downloads/cache and they should be indexed by the os and displayed in Downloads.

**Comment by thurask** [comment]
So the app said I could update Telegram from (9933) to (9934). "org.telegram.messenger 9933" appeared in Downloads with the same droid icon as other APKs in Downloads. Tapping on it brought up "Can't open file". Sharing it to Telegram sent it as "downloadfile.bin". Saving downloadfile.bin to internal memory/Downloads and renaming it to downloadfile.apk allowed me to open it and install.

**Comment by rumboalla** [comment]
Changed a few more things with the last release, let me know if it works now.
You can also check the root installs now.

**Comment by thurask** [comment]
https://paste.ee/p/VhUSJ

I think it's something that BlackBerry did to their spin of Marshmallow that prevents directly installing from the Downloads cache. I asked someone with another BlackBerry Android device (Priv running Marshmallow 6.0.1) to replicate this and the same thing happened. On the other hand, I asked someone else with a different BlackBerry Android device (KEYone running Nougat 7.1.1) and he says direct install works. None of these devices have root, and the OEM specifically set out to prevent root from happening. If I were to guess I'd say it's their security voodoo that's causing this. My main phone (Galaxy S8+ running Nougat 7.0) has absolutely zero issues with direct install.

The OS still has the capability of installing an APK, as going to APKmirror, saving the APK somewhere and invoking from Downloads works just fine. Or, starting the direct install, sharing the downloaded file from Downloads into somewhere else, saving that as an APK and installing that works too.

**Comment by rumboalla** [comment]
I'm going to close this since it looks like it's something I won't be able to fix.

**Comment by thurask** [comment]
Fair enough.

**Comment by thurask** [comment]
This might have been fixed in 1.5.7.

I managed to get one app (com.dalight.iconpack10) to install using 1.5.7 and the same DTEK60 I reported this bug with. Tap Install, APKupdater minimizes, PackageInstaller opens and the app updates. I tried with another app and got a server error, but that was due to it being paid probably.

(Unfiltered) logcat log, if necessary: https://paste.ee/p/9A1bS

**Comment by thurask** [comment]
Yeah, this seems fixed. I tested this on a BlackBerry Priv (also with Marshmallow) and 1.5.7 and direct install still worked. 1.5.7 also works on a BlackBerry KEYone (Nougat).
