### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by razeNFR** [rumboalla/apkupdater#570]
Hello,

Long time i use ApkUpdater but its only working with ApkMirror but with the installer of ApkUpdater its always fail

![Screenshot_2024-09-16-01-34-40-18_3bb3bffa89a9f6c4fe870b0aa2a0ce96](https://github.com/user-attachments/assets/4217af74-12d7-4d84-9a54-485d84990aef)

**Comment by rumboalla** [comment]
Reopen with a proper description (I don't want to guess the problems from an screenshot) detailing which sources and apps are causing the problem. Also add logs of the install failing.
