### ISSUE TITLE
APKMirror API key public

### ISSUE THREAD

**Issue by linejay** [rumboalla/apkupdater#58]
Located at [UpdaterAPKMirrorAPI.java#L44](https://github.com/rumboalla/apkupdater/blob/master/app/src/main/java/com/apkupdater/updater/UpdaterAPKMirrorAPI.java#L44)

Possible solution would be making a seperate java file with the API key like so:

```java
package com.apkupdater.updater;

public class APItokens {
    static final String APKmirrorToken = "KEY";
}
```

Then importing the class in the required files, and replacing the token with `APItokens.APKmirrorToken`.

Also don't forget to request a new token and add APKtokens.java to the .gitignore file

**Comment by rumboalla** [comment]
1) Security through obscurity won't get anyone anywhere. Disassembling the app or analyzing the traffic would get you the key in an instant.
2) The builds I sign and upload come from the exact same code that is in github. If I didn't do that who would trust my builds. I could put ads on them or a bitcoin miner and no one would be the wiser.
