### ISSUE TITLE
Scroll not smooth in search fragment

### ISSUE THREAD

**Issue by enricocid** [rumboalla/apkupdater#60]
Hi,

when Recycler view gain focus it stops the parent from scrolling smoothly

Try to add this on your child recycler view

android:nestedScrollingEnabled="false"

this option should disable recycler view scrolling. Actually I can't test this change and can't send you a PR. Try Yourself and let me know :P

**Comment by rumboalla** [comment]
Looks like that did the trick. Cheers!
