### ISSUE TITLE
Add own credentials for google play service download

### ISSUE THREAD

**Issue by rancidfrog** [rumboalla/apkupdater#64]
Currently, app uses default gsf: https://github.com/rumboalla/apkupdater/blob/master/app/src/main/java/com/apkupdater/updater/UpdaterGooglePlay.java#L141

It would be ideal to have the ability to add own ids for play service.
I.E.
https://github.com/onyxbits/raccoon4/commit/0c2196be000bed01c8c0c8c72e955355aa9bf80d

**Comment by Cormak** [comment]
@rumboalla It might be a good idea to tell users that we aren't using our own credentials when using the Play Store. Some people think our Play Services ID is being used right now.

**Comment by KehrBehr** [comment]
A small question related to this issue.  Trying to understand some things.

Is using the same Google account(s) for all users a privacy concern at all?  Is this pretty much the same as just using a Google account with the Play Store?  If so, don't the owners of the default Google account(s) used by this app have logs of all the apps downloaded / the devices used to do so, and possibly other information?

**Comment by rumboalla** [comment]
Using a shared account will give you a little more privacy compared to using your own account, but in the end Google will know what you download. The accounts used will also store some information, but since the app only uses a gsfid/token combination, the entire account is not accessible.

**Comment by Mrgts411** [comment]
on 1.5.9 u added this feature and i tried to login with my own account, i clicked on **"Yes"** so i can login, and it was stuck on **"One Moment"** with the loading wheel spinning for 2-3 minutes, after that i closed it.

is that supposed to happen or is it a bug?

**Comment by rumboalla** [comment]
This is now available.
